### ISSUE TITLE
2024-01 not available

### ISSUE THREAD

**Issue by david-256** [Shopify/shopify-node-api#1128]
## Overview

I'm working on a Shopify app for the first time. I'm using the Remix template. I'm using the latest version of `@shopify/shopify-api`. I want to make use of a graphQL field that was added to the `2024-01` API version.

When I want to change
```js
import { restResources } from "@shopify/shopify-api/rest/admin/2023-10";
```
to
```js
import { restResources } from "@shopify/shopify-api/rest/admin/2024-01";
```
it seems that `2024-01` is not available, since the latest directory within .../rest/admin is `2023-01`. 

## My Question / Feature request

When will support for 2024-01 be added?

**Comment by nboliver-ventureweb** [comment]
Also encountering this issue.

**Comment by lizkenyon** [comment]
Hi folks 👋 

Thanks for the ping! We will be releasing the 2024-01 REST resources shortly. 😄
