### ISSUE TITLE
Api Versions are out of date

### ISSUE THREAD

**Issue by furnaceX** [Shopify/shopify-node-api#116]
# Issue summary

Using `import Shopify, {ApiVersion} from '@shopify/shopify-api';`
When I print out the available ApiVersions, I get an old list:
```
ApiVersions: {
  July19: '2019-07',
  October19: '2019-10',
  January20: '2020-01',
  April20: '2020-04',
  July20: '2020-07',
  October20: '2020-10',
  Unstable: 'unstable',
  Unversioned: 'unversioned'
}
```

Seems that these are cached values.  How do I get the latest API versions to load?

**Comment by jt274** [comment]
Can confirm this. Using `ApiVersion.January21` does not work. Can probably substitute `ApiVersion.January21` for `2021-01` in the meantime.

**Comment by paulomarg** [comment]
Good catch, thanks for reporting this. I'll add that version right away!
