### ISSUE TITLE
No instructions on how to make post request to rest api

### ISSUE THREAD

**Issue by offsec1** [Shopify/shopify-node-api#120]
# No documentation provided on how to use shopify-api properly

I tried to figure out how to make post requests to the sopify admin rest api but I can't figure it out. That's what I expected the request to look like:
```
const client = new Shopify.Clients.Rest(shop, accessToken);

        await client.post({
          path: 'script_tags',
          data: {
            script_tag: {event: "onload", src: "url"}
          }
        }).catch(console.log)
```

This request resolves in an Error: 
` TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received null`

There is no documentation provided on what format the data parameter should have.

**Comment by paulomarg** [comment]
Hey @offsec1, thank you for bringing this up! I believe your request is correct, but it is lacking the `type` parameter, so it would look something like this:
```ts
        await client.post({
          path: 'script_tags',
          type: DataType.JSON, // or 'application/json'
          data: {
            script_tag: {event: "onload", src: "url"}
          }
        })
```

Please let us know if that solves the problem for you, but we'll look into better documenting this method / whether it makes sense to default the type to `JSON` for REST requests.

**Comment by offsec1** [comment]
Hey @paulomarg, thanks for the quick response! That did the trick. I'd vote for the JSON default type :)

**Comment by trollkotze** [comment]
> Hey @offsec1, thank you for bringing this up! I believe your request is correct, but it is lacking the `type` parameter, so it would look something like this:
> 
> ```ts
>         await client.post({
>           path: 'script_tags',
>           type: DataType.JSON, // or 'application/json'
>           data: {
>             script_tag: {event: "onload", src: "url"}
>           }
>         })
> ```
> 
> Please let us know if that solves the problem for you, but we'll look into better documenting this method / whether it makes sense to default the type to `JSON` for REST requests.

It's still not documented and the "type" argument is omitted in examples as found here: https://shopify.dev/api/admin-rest
