### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by paulomarg** [Shopify/shopify-node-api#121]
## Overview/summary

Now that the library has been released, we noticed a couple of pain points that we can help remedy via documentation. This PR aggregates them so we can address them at once.

1. Document the methods and parameters for the REST and GraphQL clients (using the same table format from the `withSession` docs).
1. Add a concrete production-valid example of how to use `CustomSessionStorage` in the session notes. We could show how to implement the callbacks using Redis.
2.1. We may want to consider adding a few tips (and what-not-to-dos!) on using this feature to help developers choose their preferred method.

## Checklist

- [X] I have described this enhancement in a way that is actionable (if possible)

**Comment by Wilddata** [comment]
It would be nice to have examples/doc to show how to make requests using private apps

**Comment by paulomarg** [comment]
Thanks @Wilddata! In case anyone ends up here from a search, to use private apps you should set
```ts
Shopify.Context.initialize({
  ...
  IS_PRIVATE_APP: true,
});
```

The clients work the same as for public / custom apps, but you don't need an access token. You could make REST requests like so for private apps:

```ts
const client = new Shopify.Clients.Rest(shop);
await client.get({ ... });
```

We'll add some information around that to the docs as well.

**Comment by thecodepixi** [comment]
Based on #124 we may also need better documentation around webhooks 🤔

**Comment by paulomarg** [comment]
I think webhooks are fairly well covered since they're mentioned at the top level of the docs. The changes you made to the GraphQL client should make the purpose of the `query` param more evident (even if it may never be used for GraphQL), but we could add a very simple example of a query with variables to the docs to make that clearer.

**Comment by supa-freak** [comment]
It would be highly appreciated to get some example for production. 
It would clarify the difference of the SESSION_STORAGE object with its 3 methods and the 
ACTIVE_SHOPIFY_SHOPS object (as it is used shopify's widely used node app boilerplate) and how to effectively persist them.

**Comment by mitas1** [comment]
Maybe I'm just blind but I want to create `CustomSessionStorage` using typescript. How can I import Session type? `import { Session } from @shopify/shopify-api` does not work for me.

**Comment by mitas1** [comment]
I found the way: `import { Session } from '@shopify/shopify-api/dist/auth/session'`. But cannot we expose it in a more reachable point?

Btw: @paulomarg would not be helpful having some kind of serialization and deserialization of `Session` so that it will be easier to store and load session tokens? E.g.:
```ts
const session: Session = Session({id: "id"});
const sessionPlainObject = session.serialize() // returns just plain js object
const session2: Session = Session(sessionPlainObject);
```

**Comment by paulomarg** [comment]
Hey folks, thanks for your comments! Here are my thoughts:

- @supa-freak we are actually adding a Redis-based example to the docs, to make it easier to see how this is supposed to work
- We can't really cover how to store `ACTIVE_SHOPIFY_SHOPS` because different apps can use different means, but Redis is also a valid option for that. You can also store it in your database for a more 'permanent' solution, as long as you make sure to delete it using the `APP_UNINSTALLED` webhook.
- @mitas1 you can create Session objects using `new Shopify.Session.Session();` from the main import.
- Yes, we were actually working on adding support for loading Sessions from a plain object: https://github.com/Shopify/shopify-node-api/pull/126. With this you should be able to do this:
```ts
const session: Session = new Session({id: "id"});

function storeSession(session) {
  MyStorage.store(JSON.stringify(session));
}

function loadSession(id) {
  const json = MyStorage.load(id);
  return JSON.parse(json);
}
```
So you can just return JSON from your `loadSession` callback and we'll convert it to a proper Session object for you.

**Comment by kato-takaomi-ams** [comment]
https://github.com/Shopify/shopify-node-api/blob/main/docs/issues.md#notes-on-session-handling

Actually I had to import Session Class from dist.

src/my_session_storage.ts
```javascript
- import { SessionStorage } from '@shopify/shopify-api';
+ import { Session } from '@shopify/shopify-api/dist/auth/session';

  async function storeCallback(session: Session): Promise<boolean> { ... }
  async function loadCallback(id: string): Promise<Session | Record<string, unknown> | undefined> { ... }
  async function deleteCallback(id: string): Promise<boolean> { ... }

  const mySessionStorage = new Shopify.Session.CustomSessionStorage(
    storeCallback,
    loadCallback,
    deleteCallback,
  );
```

**Comment by paulomarg** [comment]
Thanks @kato-takaomi-ams, we should probably make that easier to use as a type.

**Comment by marvinhuebner** [comment]
> Thanks @Wilddata! In case anyone ends up here from a search, to use private apps you should set
> 
> ```ts
> Shopify.Context.initialize({
>   ...
>   IS_PRIVATE_APP: true,
> });
> ```
> 
> The clients work the same as for public / custom apps, but you don't need an access token. You could make REST requests like so for private apps:
> 
> ```ts
> const client = new Shopify.Clients.Rest(shop);
> await client.get({ ... });
> ```
> 
> We'll add some information around that to the docs as well.

@paulomarg from where do you get the `shop` object which are you passing in `Shopify.Clients.Rest`? Could you provide a full example how to use it with private apps? Would be awesome! Thanks in advance.
