### ISSUE TITLE
Upgrade to new Shopify API version without upgrading `@shopify/shopify-api` package

### ISSUE THREAD

**Issue by sudhxnva** [Shopify/shopify-node-api#1230]
## Overview/summary

I have an app that is currently on `@shopify/shopify-api` version 5.3.0 and using the API version October 2022 which had support until the October of 2023. I wasn't able to get to upgrading the API earlier due to other commitments, but now that I have been trying to bump up the package version to v9, I've noticed a huge set of breaking changes from v5 to v6 which will take me days to implement and test thoroughly. Since I don't have that kind of time to devote right now, is it possible for me to just hard-code a newer API version like so? Haven't gone through the source code of this library to check, so apologies in advance if my question is silly.

```js
Shopify.Context.initialize({
    ...otherProps,
    API_VERSION: "2023-01", // Previously ApiVersion.October22,
});
```

I understand that the APIs themselves might have breaking changes, but I've made sure that the version I want to upgrade to doesn't have breaking changes in the endpoints I'm currently using.

**Comment by paulomarg** [comment]
Hi! As a temporary workaround, you could try using a string and then casting it to `ApiVersion` - TypeScript should be ok with that conversion.

Since there is no real action we can take here, I'll close the issue, but let us know if you have any problems.
