### ISSUE TITLE
Passing custom ARN argument when registering EventBridge webhooks

### ISSUE THREAD

**Issue by rdunk** [Shopify/shopify-node-api#125]
Maybe more of a question as I'm assuming I may have misinterpreted the docs.

When registering EventBridge webhooks, the [`arn`](https://github.com/Shopify/shopify-node-api/blob/da4cfc200350bc1b90d6e271f1bdb875f7b5bb01/src/webhooks/registry.ts#L116) argument [looks like it's built](https://github.com/Shopify/shopify-node-api/blob/da4cfc200350bc1b90d6e271f1bdb875f7b5bb01/src/webhooks/registry.ts#L147) as a URL in the following format:

`https://${Context.HOST_NAME}${path}`

[This tutorial](https://shopify.dev/tutorials/manage-webhook-events-with-eventbridge?itcat=partner_blog&itterm=shopify_webhooks#4-create-webhook-subscriptions-for-eventbridge) suggests using the Partner event source ARN which as far as I can tell, for Shopify events, follow the format:

`arn:aws:events:region::event-source/aws.partner/shopify.com/id/name`

Is there a way to set the ARN argument manually, or am I missing something here? Thanks.

**Comment by paulomarg** [comment]
This is a great point @rdunk, right now we're always using an HTTP address. We'll look into supporting other alternatives!

**Comment by mkevinosullivan** [comment]
Closing this, as the PR supporting this is now merged.

Thanks @rdunk for the great contribution 👍🏻
