### ISSUE TITLE
port verifyToken from koa-shopify-auth

### ISSUE THREAD

**Issue by kato-takaomi-ams** [Shopify/shopify-node-api#133]
[verify-tokens.ts](https://github.com/Shopify/koa-shopify-auth/blob/b3a644bf7955a658c2b5c0347e73170934bdd4e6/src/verify-request/verify-token.ts#L13)

I want to use it like this.
```ts
if (!Shopify.Auth.verifyToken(req, res, "online") {
  return res.redirect(`/auth?${req.query.shop}`);
}
```

**Comment by paulomarg** [comment]
Hey @kato-takaomi-ams, thanks for your suggestion, but I'm not sure it would be worth porting that function over as it is. In essence, all it does is:
```ts
const session = await Shopify.Utils.loadCurrentSession(req, res, mode === 'online');
if (
  session &&
  Shopify.Context.SCOPES.equals(session.scope) &&
  session.accessToken &&
  (!session.expires || session.expires >= new Date())
) {
  // Session is OK!
} else {
  // Session is stale!
}
```

You could write a middleware that does that and it would have the same behaviour.

In writing this however, I realize that one possible improvement we could make in the future would be to add a `isActive()` method to `Session`, so this code would become:

```ts
const session = await Shopify.Utils.loadCurrentSession(req, res, mode === 'online');
if (session && session.isActive()) {
  // Session is OK!
} else {
  // Session is stale!
}
```

That would make this check nice and clean, and allow us to more easily evolve this behaviour.

**Comment by kato-takaomi-ams** [comment]
@paulomarg Thank you for your reply. I think `session.isActive()` is very good.
To verify scope, I need `Shopify.Context.SCOPES`. So maybe better to have a method like `Shopify.Auth.verifySession(session)`.

**Comment by ilugobayo** [comment]
@paulomarg Hello, do you know why `Shopify.Utils.loadCurrentSession` half the time returns undefined in `"/"`? This makes it impossible for me to compare the expiration date and scopes in order to decide whether I need to redirect the merchant to `"/auth"` or the app.
