### ISSUE TITLE
TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by danhsucowboy** [Shopify/shopify-node-api#139]
# Issue summary
Hi shopify-node-api team,

Thanks for making this node API.

I am trying to build an embedded app with Vue/Koa.js, I just start by following the tutorial of [@shopify/koa-shopify-auth](https://github.com/Shopify/koa-shopify-auth). However, when I tried to run the example app via command `node server.js`,
it return an error said:
```node.js
Shopify.Context.initialize({
                ^
TypeError: Cannot read property 'initialize' of undefined
``` 
It confused me, so I came here following the getting start tutorial of [@shopify/shopify-node-api](https://github.com/Shopify/shopify-node-api/blob/main/docs/getting_started.md#running-your-app), and carefully checked every input arguments(API_KEY, API_SECRET_KEY, SCOPES, HOST, all these value are correct).

Unfortunately, I got just the same error.

## Expected behavior

I expected the example app can successfully executed, or at least the function `Shopify.Context.initialize` could work.

## Actual behavior

when I tried to run the example app via command `node server.js`,
it return an error said:
```node.js
Shopify.Context.initialize({
                ^
TypeError: Cannot read property 'initialize' of undefined
``` 
Even I checked the tutorial at here, it still end with same the error.

## Steps to reproduce the problem

1. Setup the files
2. type `node server.js`

## Reduced test case
Following is my code(sever.js and package.json):

**server.js**
```javascript
import 'isomorphic-fetch';
import dotenv from 'dotenv';
import Koa from 'koa';
import session from 'koa-session'; 
import shopifyAuth, {default as verifyRequest} from '@shopify/koa-shopify-auth';
import Shopify, {ApiVersion} from '@shopify/shopify-api';

dotenv.config();
const port = parseInt(process.env.port, 10) || 3000;
const {SHOPIFY_API_SECRET, SHOPIFY_API_KEY} = process.env;

//initialize the library
Shopify.Context.initialize({
    API_KEY: SHOPIFY_API_KEY,
    API_SECRET_KEY: SHOPIFY_API_SECRET,
    SCOPES: [process.env.SHOPIFY_APP_SCOPES],
    HOST_NAME: process.env.SHOPIFY_APP_URL.replace(/^https:\/\//, ''),
    IS_EMBEDDED_APP: true,
    API_VERSION: ApiVersion.October20,
    SESSION_STORAGE: new Shopify.Session.MemorySessionStorage()
  });

const server = new Koa();
server.keys = [SHOPIFY_API_SECRET];
server.use(session(server))

.use(
    shopifyAuth({
        afterAuth(ctx){
            const {shop, accessToken} = ctx.session;
            console.log('First Trial Success!', accessToken);
            ctx.redirect('/');
        },
    }),
)

.use(verifyRequest())

.use(ctx => {
    ctx.body = '😎';
});

server.listen(port, ()=>{
    console.log('> Ready on http://localhost:${port}');
});
```
**package.json**
```json
{
  "name": "koala",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Dan Hsu",
  "license": "ISC",
  "dependencies": {
    "@shopify/app-bridge-utils": "^1.29.0",
    "@shopify/koa-shopify-auth": "^4.0.2",
    "@shopify/shopify-api": "^1.1.0",
    "@types/koa": "^2.13.1",
    "dotenv": "^8.2.0",
    "isomorphic-fetch": "^3.0.0",
    "koa": "^2.13.1",
    "koa-router": "^8.0.8",
    "koa-session": "^6.1.0"
  }
}
```
---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by NoahHowadt** [comment]
Hey, I had the same issue, fixed it by installing babel. My exact steps were:

1. Installing `@babel/core`, `@babel/preset-env` and `@babel/register`
2. Adding an `index.js` file like so:
```
require("@babel/register");

// Import the rest of our application.
module.exports = require("./app.js");
```
3. Adding the following babel config file:
```
module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        targets: {
          esmodules: true,
        },
      },
    ],
  ],
  ignore: ["node_modules"],
};
```
So when you run the `index.js` file, the issue should be resolved. Hope that helps!

**Comment by danhsucowboy** [comment]
Hi @NoahHowadt, Thank you for your idea. It works! 

Just have a little question, why the `index.js` file need to write in es5?

```JavaScript
require("@babel/register");

// Import the rest of our application.
module.exports = require("./app.js");
```

**Comment by NoahHowadt** [comment]
Hey @danhsucowboy, I'm glad it worked for you!

As to why the `index.js` file is in es5, I'm sorry, I don't know. I just took the code from the [shopify-app-node github repo](https://github.com/Shopify/shopify-app-node/blob/66ff3abf121ebe581770f1265534b17e0ca8ff55/server/index.js). Tried to convert it to es6, but it didn't seem to work so I just left if as it is.

**Comment by danhsucowboy** [comment]
Got it, thank you very much!
I'll close this issue.

**Comment by m-allanson** [comment]
In case this helps anyone else. I'm using TypeScript, and these approaches both worked for me:

```js
import { Shopify as S } from "@shopify/shopify-api";

S.Context.initialize({
  // code here
});
```

```js
import Shopify from "@shopify/shopify-api";

// @ts-expect-error
const S = Shopify.default;

S.Context.initialize({
  // code here
});
```

**Comment by matija2209** [comment]
That worked thanks. Their doc on Github are wrong then
https://github.com/Shopify/shopify-node-api/blob/main/docs/getting_started.md#set-up-environment
