### ISSUE TITLE
Add Offline Mode to graphqlProxy

### ISSUE THREAD

**Issue by zzyrd** [Shopify/shopify-node-api#141]
## Overview/summary

Add a feature to `Shopify.Utils.graphqlProxy(ctx.req, ctx.res)` to handle case where the shop is authenticated under accessMode=offline
...

## Motivation

> What inspired this enhancement?
Under the codebase of [graphql_proxy.ts](https://github.com/Shopify/shopify-node-api/blob/main/src/utils/graphql_proxy.ts), the function called ` loadCurrentSession` to load the current session. However, it didn't list out the third argument, which is a boolean type of whether the session is online or offline. And the default value is online. 
Thus, no matter what type of accessMode the developers wanted, this function would only call loadCurrentSession with the online option, which would cause an error either not found the session or unauthorized if they used offline accessMode.
Currently, it works fine with the online mode, but it would be better to add an extra option for developers to choose the online/offline in order to use `graphqlProxy` easily.
...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
@zzyrd this is done by design, please see detailed [comment](https://github.com/Shopify/shopify-node-api/issues/140#issuecomment-801053492) on #140
