### ISSUE TITLE
Error: Context has not been properly initialized. Please call the .initialize() method to setup your app context object

### ISSUE THREAD

**Issue by valorloff** [Shopify/shopify-node-api#144]
# Issue summary
Right after migrate from old api to "Shopify.context" based api i started getting this error during attempt install embedded app

Immediately after changes have been made to the server.js, based on [tutorial](https://github.com/Shopify/shopify-app-node/blob/tutorial_charge_with_billing_api/server.js), i can't install app  by /auth?shop=${shop} url, due to Error: Context has not been properly initialized. Please call the .initialize() method to setup your app context object

## Actual behavior
.env is completed by all data in accordance with docs and nice logs before start auth process
```
createShopifyAuth({
      async afterAuth(ctx) {
```
Also Shopify.context logs ok during server starts. But /auth?shop=${shop} request crashes with above error.

package.json:
```
"dependencies": {
    "@apollo/client": "^3.3.9",
    "@google-cloud/storage": "^5.8.0",
    "@shopify/app-bridge-react": "^1.29.0",
    "@shopify/app-bridge-utils": "^1.29.0",
    "@shopify/koa-shopify-auth": "^4.0.3",
    "@shopify/polaris": "^6.0.1",
    "@shopify/polaris-icons": "^4.5.0",
    "@shopify/shopify-api": "^1.2.0",
    "@zeit/next-css": "^1.0.1",
    "dotenv": "^8.2.0",
    "graphql": "^15.5.0",
    "history": "^5.0.0",
    "isomorphic-fetch": "^3.0.0",
    "koa": "^2.13.1",
    "koa-router": "^10.0.0",
    "lodash": "^4.17.20",
    "next": "^10.0.6",
    "nodemon": "^2.0.7",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "request": "^2.88.2",
    "store-js": "^2.0.4",
    "uuid": "^8.3.2"
  },
```
Can you advise something?

**Comment by paulomarg** [comment]
Hey @valorloff, I think the problem you're seeing is because you're including both the `@shopify/koa-shopify-auth` and `@shopify/shopify-api` packages in your `package.json`.

The koa-specific package actually already includes the base API library, so you shouldn't need to include it directly as well - since the Context object centralizes the configs, including both packages will probably leave your app with 2 copies of it, which could lead to the error message you're seeing.

Could you let us know if removing `@shopify/shopify-api` from package.json fixes the problem?

**Comment by valorloff** [comment]
Thanks for quick response!
No, it not fixes problem.
If `uninstall @shopify/shopify-api`, where can I import Shopify and ApiVersion from ?
I get `Error: Cannot find module '@shopify/shopify-api'` 
This is your sample app:
```
.......
const { default: createShopifyAuth } = require('@shopify/koa-shopify-auth');
const { verifyRequest } = require('@shopify/koa-shopify-auth');
const { default: Shopify, ApiVersion } = require('@shopify/shopify-api');
....
```

**Comment by nolandg** [comment]
@paulomarg Can you please answer the question of where can we import `Shopify` and `ApiVersion` from if we don't import `@shopify/shopify-api`? How is your example app and tutorial working if both packages aren't supposed to be imported? I'm facing the same problem as @valorloff but simply uninstalling and reinstalling isn't changing anything. Thanks!

**Comment by nolandg** [comment]
@valorloff How is that avoiding a `@shopify/shopify-api` import as paulomarg advised to do?

**Comment by ZPetrovich** [comment]
@nolandg Just delete **package-lock.json** and **node_modules** and run `npm i @shopify/koa-shopify-auth`. It will download transitive dependency of `@shopify/shopify-api` and you will be able to use your imports `const { default: Shopify, ApiVersion } = require('@shopify/shopify-api');`
