### ISSUE TITLE
Cannot complete OAuth process. Could not find an OAuth cookie for shop url

### ISSUE THREAD

**Issue by Geebrox** [Shopify/shopify-node-api#151]
# Issue summary

Getting error with message: _**Cannot complete OAuth process. Could not find an OAuth cookie for shop url:**_

## Expected behavior

`validateAuthCallback` shouldn't throw an error

## Actual behavior

`/auth/callback` route throws an error
This happens while validating auth callback (route: /auth/callback)
I used the code from the docs (README.md)

## Steps to reproduce the problem

1. Initialize Shopify Context
```
Shopify.Context.initialize({
    API_KEY: settings.SHOPIFY_API_KEY,
    API_SECRET_KEY: settings.SHOPIFY_API_SECRET,
    SCOPES: settings.SHOPIFY_API_SCOPES.split(','),
    HOST_NAME: settings.HOST.replace(/https:\/\//, ''),
    API_VERSION: ApiVersion.October20,
    IS_EMBEDDED_APP: true,
    SESSION_STORAGE: new Shopify.Session.MemorySessionStorage()
  })
```
2. Add auth route in my case is `/login`
```
router
    .get('/login', async (req: Request, res: Response) => {
      const { shop } = req.query

      if (typeof shop !== 'string' || !Shopify.Utils.validateShop(shop)) {
        res.status(400).send('Invalid shop parameter')
        return
      }

      try {
        const authRoute = await Shopify.Auth.beginAuth(
          req,
          res,
          shop,
          '/auth/callback',
          true
        )

        return res.redirect(authRoute)
      } catch (error) {
        log.error(error)
        res.status(500).send('Unexpected error occured')
      }
    })
```
3. Add auth callback route in my case `/auth/callback`
```
router
    .get('/auth/callback', async (req: Request, res: Response) => {
      try {
        await Shopify.Auth.validateAuthCallback(
          req,
          res,
          (req.query as unknown) as AuthQuery
        )

        return res.redirect('/')
      } catch (error) {
        log.error(error)
        res.status(500).send('Unexpected error occured')
      }
    })
```
4. Open the app with the route `/auth?shop=your.shop.url`

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by Geebrox** [comment]
clone of #130 Sorry for off top, I found the same issue, after I opened the new one.

**Comment by sahedAnis** [comment]
Hello, what does Shopify.Utils.validateShop do ? Does it return false when shop does not exist ?

**Comment by Geebrox** [comment]
> Hello, what does Shopify.Utils.validateShop do ? Does it return false when shop does not exist ?

It tests string for match with valid Shopify shop name using regexp
