### ISSUE TITLE
new Shopify.Clients.Graphql is not working, "Domain .. is not valid",  applies token as domain

### ISSUE THREAD

**Issue by MarcoDo99** [Shopify/shopify-node-api#158]
# Issue summary

Write a short description of the issue here ↓
new Shopify.Clients.Graphql(shop, accessToken); is not working.  

## Expected behavior
The code I am calling.

```typescript
addScriptTag = () => {
const shop = "myshop.myshopify.com;
const accessToken = "shpat_xxx"
console.log("beforeClient", shop, accessToken)
const client = new Shopify.Clients.Graphql(shop, accessToken);
//error occurs when calling "Shopify.Clients.Graphql(shop, accessToken);"
// ...
}
// (I have added logs to the graphQL_client.js code)

function GraphqlClient(domain, token) {
// ...
console.log("graphql_client.js", domain, token)
// ...
this.client = new http_client_1.HttpClient(this.domain);
```

When I call addScriptTag(shop, accessToken), I receive the following logs:

```
beforeClient bobbetest.myshopify.com shpat_xxx
graphql_client.js shpat_xxx myshop.myshopify.com
InvalidShopError: Domain shpat_xxx is not valid. //this error is thrown in http_client.js since the access token is no valid url
...
graphql_client.js myshop.myshopify.com shpat_xxx
```

What do you think should happen?
Since my code is almost equal to the Instruction guide, and equal to the Shopify Node.js and React tutorial, I expected it to work.

## Actual behavior

What actually happens?
So as you can see, the GraphQl-client gets called twice. One time with the domain and accessToken parameter switched up, which causes the program to break. (see the two logs "graphQL_client.js ...") I think this is a bug not caused by my programming, since the log "beforeClient myshop.myshopify.com shpat_xxx" is only logged once. 
I do not know how I should proceed to fix this bug.

the complete error message:
```
InvalidShopError: Domain shpat_xxx is not valid
┃     at InvalidShopError.ShopifyError [as constructor] (.../node_modules/@shopify/shopify-api/dist/error.js:13:28)
┃     at new InvalidShopError (.../webstory/node_modules/@shopify/shopify-api/dist/error.js:31:42)
┃     at new HttpClient (.../node_modules/@shopify/shopify-api/dist/clients/http_client/http_client.js:25:19)
┃     at new GraphqlClient (.../node_modules/@shopify/shopify-api/dist/clients/graphql/graphql_client.js:21:23)
┃     at _callee$ (.../server/handlers/mutations/addScriptTag.js:26:18)
┃     at tryCatch (.../node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:63:40)
┃     at Generator.invoke [as _invoke] (.../node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:293:22)
┃     at Generator.next (.../node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:118:21)
┃     at asyncGeneratorStep (.../server/handlers/mutations/addScriptTag.js:8:103)
┃     at _next (.../server/handlers/mutations/addScriptTag.js:10:194)
┃     at .../server/handlers/mutations/addScriptTag.js:10:364
┃     at new Promise (<anonymous>)
┃     at .../server/handlers/mutations/addScriptTag.js:10:97
┃     at addScriptTag (.../server/handlers/mutations/addScriptTag.js:6:26)
┃     at _callee2$ (.../server/server.js:51:9)
┃     at tryCatch (.../node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:63:40)
```

**Comment by mkevinosullivan** [comment]
Hi @MarcoDo99,

The error being thrown is due to your shop name failing a regular expression validation.  (I'm assuming the `myshop.myshopify.com` is just an example above?)

Some information about the shop domain validation can be found at https://shopify.dev/tutorials/authenticate-with-oauth#step-3-confirm-installation.  The regular expression used is:
```
/^[a-zA-Z0-9][a-zA-Z0-9-]*\.myshopify\.com[/]*$/
```

**Comment by MarcoDo99** [comment]
Hi @mkevinosullivan,
sorry for the late response:

1. version:
npm list @shopify/shopify-api
shopify-app-node@1.0.0 <path>
└─┬ @shopify/koa-shopify-auth@4.0.3
  └── @shopify/shopify-api@1.2.0

2. This is exactly what confuses me too. See the following code fragments: (I created my project with Shopify-CLI)
server.js file
`app.prepare().then(async () => {
  const server = new Koa();
  
  const router = new Router();
  server.keys = [Shopify.Context.API_SECRET_KEY];
  server.use(
    createShopifyAuth({
      async afterAuth(ctx) {
        // Access token and shop available in ctx.state.shopify
        const { shop, accessToken, scope } = ctx.state.shopify;
        ACTIVE_SHOPIFY_SHOPS[shop] = scope;
        
        // This is where I call the addScriptTag function
        addScriptTag(shop, accessToken); 

        const response = await Shopify.Webhooks.Registry.register({
          shop,
          accessToken,
          path: "/webhooks",
          topic: "APP_UNINSTALLED",
          webhookHandler: async (topic, shop, body) =>
            delete ACTIVE_SHOPIFY_SHOPS[shop],
        });

        if (!response.success) {
          console.log(
            `Failed to register APP_UNINSTALLED webhook: ${response.result}`
          );
        }

        
        // Redirect to app with shop parameter upon auth
        ctx.redirect(`/?shop=${shop}`);
      },
    })
  );`

addScriptTag function:
`const { default: Shopify } = require('@shopify/shopify-api');


const scriptTagUrl = "https://some.s3.eu-central-1.amazonaws.com/scripttag.js";

export const addScriptTag = async (accessToken, shop) => {
  const query = `mutation {
    scriptTagCreate(
      src: ${scriptTagUrl}
    )
    {
        scriptTag {
            id
          }
          userErrors {
            field
            message
          }
        }
    }
  }`;

  
  console.log("Before Client", accessToken, shop)
  
  const client = new Shopify.Clients.Graphql(shop, accessToken);
  

        const response = await client.query({
        data: query,
        });
        
   return response.body.data.scriptTagCreate.scriptTag.id;
  
    return 0;
  
};
`

Summary: in server.js file I call the addScriptTag file after Auth which works so far.
In addScripttag, I have the correct shop and accessToken parameters which are then used to 
` const client = new Shopify.Clients.Graphql(shop, accessToken);`
This is where the error happens.


For information: I have created my app with Shopify-CLI: "shopify create node"
Shopify-CLI version: 1.7.1

**Comment by MarcoDo99** [comment]
sorry for the mistake, I switched up the parameter order.
