### ISSUE TITLE
Session scope check fails when scope is undefined

### ISSUE THREAD

**Issue by axmachina** [Shopify/shopify-node-api#159]
# Issue summary

This fails when session is present with scope undefined.

``
if (session) {
      const scopesChanged = !Shopify.Context.SCOPES.equals(session.scope);

      if (!scopesChanged && session.accessToken && (!session.expires || session.expires >= new Date())) {
        ctx.cookies.set(TOP_LEVEL_OAUTH_COOKIE_NAME);
        await next();
        return;
      }
    }
``

## Expected behavior

Should invalidate session and initiate oauth.

## Actual behavior

What actually happens?

The failure happens downstream in shopify api,

``
TypeError: Cannot read property 'map' of undefined
    at new AuthScopes (/node_modules/@shopify/shopify-api/dist/auth/scopes/index.js:14:35)
``

## Steps to reproduce the problem

I'm unable to reproduce this reliably, but can manually remove scope from session to test.

**Comment by carmelal** [comment]
Hi @axmachina, thank you for bringing this up. I've moved this issue to the `shopify-node-api` repo to help us keep track of it - this is where the underlying issue is, and we're currently working on a solution.
