### ISSUE TITLE
Handling app proxy from Shopify

### ISSUE THREAD

**Issue by Geebrox** [Shopify/shopify-node-api#163]
I am wondering if there is a way to check if the user (store) is authenticated when the request comes from the Shopify proxy? How do I get a session for a store (offline/online) when a user (store) has sent a request to the app's server using a script that is injected with a script tag? Or are there any other ways to check if the request sent with exactly Shopify app proxy? The current problem is that you can fetch store data from the app using any shop parameter in the request and all requests coming to the path `/proxy/*` bypass authentication check

**Comment by tanema** [comment]
You cannot get authentication though app proxies. This is not what they are for. App proxies are design to change online stores, an area of shopify that is unauthenticated. 

>  Or are there any other ways to check if the request sent with exactly Shopify app proxy?

The request is signed with a sha-256 HMAC and this should be verified before you do anything with the request. This verifies that the request originated from shopify. Please see more information here: https://shopify.dev/tutorials/display-dynamic-store-data-with-app-proxies

This does not seem to be an issue with the library, please only use github issues for issues with the library. In the future use the shopify forums for support.
