### ISSUE TITLE
callbackUrl Address is invalid on webhook registration

### ISSUE THREAD

**Issue by psmod2** [Shopify/shopify-node-api#194]
Hello,

I'm using [this guide to setup webhooks](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/listen-for-store-events-with-webhooks) in my Shopify app.

Specifically I have the following code:

```
         ACTIVE_SHOPIFY_SHOPS[shop] = scope;
         const registration = await Shopify.Webhooks.Registry.register({
          shop,
          accessToken,
          path: '/webhooks',
          topic: 'APP_UNINSTALLED',
          apiVersion: ApiVersion.October20,
          webhookHandler: (_topic, shop, _body) => {
            console.log('App uninstalled');
            delete ACTIVE_SHOPIFY_SHOPS[shop];
          },
        });

        if (registration.success) {
          console.log('Successfully registered webhook!');
        } else {
          console.log('Failed to register webhook', registration.result.data.webhookSubscriptionCreate.userErrors);
        }
```

However the webhook fails to register each time giving me the error:

```
Failed to register webhook [
  {
    field: [ 'webhookSubscription', 'callbackUrl' ],
    message: 'Address is invalid'
  }
]
```

Any ideas - I can't see anywhere to specify the callback / where is it getting it from to call it invalid?

Thanks.

**Comment by brendonchen-shopify** [comment]
The url is based on the environment settings. Can you check if step 2 ("Make sure ngrok is running, and that you’ve added the HTTPS version of your ngrok forwarding URL to your .env file") from the guide is done with the correct data?

**Comment by psmod2** [comment]
Thanks - my skeleton, was based on an older tutorial so I was not setting up my server.js file as per this newer tutorial. Used waybackmachine to get the old tutorial. All good now. works.
