### ISSUE TITLE
passing query parameter to client get request

### ISSUE THREAD

**Issue by mkamalkayani** [Shopify/shopify-node-api#195]
How to pass query parameter to the client.get()?

I have tried passing the query key as shown below (and some other variations with .json and ?) but I get the whole assets array. I am not sure if I am doing it incorrectly or it's a bug.

```
client.get({
    path: `themes/${mainTheme.id}/assets`,
    query: "asset[key]=templates/index.liquid",
  })
  ```
  
  However, I am able to get the desired result using axios.
  
  ```
const config = {
    baseURL: `https://${session.shop}`,
    headers: {
      "X-Shopify-Access-Token": session.accessToken,
      "X-Shopify-Shop-Domain": session.shop,
    },
  };
  const result = await axios.get(
    `/admin/api/2021-04/themes/${mainTheme.id}/assets.json?asset[key]=templates/index.liquid`,
    config
  );
  ```
  
  Please update the docs with more examples.

**Comment by hta218** [comment]
The note in the documentation says about `query`:
> An optional query **object** to be appended to the request

So I guess we should pass an object there
This is my implementation (It worked!)

```js
const client = new Shopify.Clients.Rest(shop, accessToken);

const response = await client.get({
	path: `themes/${themeId}/assets`,
	query: { "asset[key]": "config/settings_data.json" },
})
```

The `response` should look like this

```js
{
	// headers, pageInfo...
	body: {
		// other keys
		asset: {
			// other keys...
			value: "Here your file"
		}
	}
}

console.log(response.body.asset.value) // Expect: "Here your file"
```

**Comment by mkamalkayani** [comment]
@hta218 Thanks man. That was helpful.
