### ISSUE TITLE
Context uninitialized error

### ISSUE THREAD

**Issue by unlocomqx** [Shopify/shopify-node-api#208]
# Issue summary

Using yarn or any other package manager that doesn't necessarily flatten packages

I have `@shopify/shopify-api` in my `package.json` which resolves to version X1

The version of `@shopify/shopify-api` that is in the `package.json` of `@shopify/koa-shopify-auth` resolves to version X2

My app imports context from `@shopify/shopify-api` and inits it but `@shopify/koa-shopify-auth` uses the "internal" context now located in `/node_modules/@shopify/koa-shopify-auth/node_modules/@shopify/shopify-api/dist/context.js`

I'm setting up the "wrong" context which results in the uninit error

## Steps to reproduce (Not consistent)
1. yarn
2. rm -rf node_modules
3. yarn add @shopify/koa-shopify-auth@^4.1.0  
4. yarn add @shopify/shopify-api
5. ls node_modules/@shopify/koa-shopify-auth/node_modules/@shopify/shopify-api/dist/context.js 
If the sub-package exists, then that will cause the bug

I was able to avoid the issue by using the same version that the auth package uses but it's best to use shopify-api as a peer dependency imo

**Comment by akospaska** [comment]
Hello,

 I have the same issue.

Could you please tell me how can i avoid exactly?

If i install this package it crashes.

Which version of this package should i install it?

Thank you in advance.

Akos

**Comment by akospaska** [comment]
Hey Mate,

Thank you for your fast help.

Now the APP didn't crash.

Let's see how it works.

I can't describe how thankfull i am.
