### ISSUE TITLE
Pub Sub subscription creation

### ISSUE THREAD

**Issue by AlfredAfutu** [Shopify/shopify-node-api#214]
# Issue summary

Registering pub sub webhook doesn't publish to pub sub.

## Expected behavior
Webhook should be published to pub sub

## Actual behavior

The registration is successful but webhook is not sent to pub sub

This is my code for registering the webhook

`
const ordersPaidWebhookResponse = await Shopify.Webhooks.Registry.register({
          shop,
          accessToken,
          path: "pubsub://<PROJECT_ID>:order-paid-on-shopify",
          topic: "ORDERS_PAID",
          webhookHandler: async (topic, shop, body) => {
            console.log("Orders paid sent to pub sub");
          }
        });
`
Maybe i'm doing something wrong?

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [✅ ] I have described this issue in a way that is actionable (if possible)

**Comment by mikedasilva** [comment]
It's hard to tell what the problem could be from this however it might be a missing scope or that the permission hasn't been granted in GCP.

Please take a look at this video for how to enable Pub/Sub in your app. It quickly walks you through getting it working end-to-end.
https://www.youtube.com/watch?v=m9MQyRWnMdU

**Comment by AlfredAfutu** [comment]
Thanks for the video link. I'll check it out and give an update.

**Comment by AlfredAfutu** [comment]
@mikedasilva your video is heaven sent. The issue was that i didn't update the API_VERSION to July21 and set the deliveryMethod to DeliveryMethod.PubSub. All other setup were correct. Thanks a lot.
