### ISSUE TITLE
 Error with shopify auth callback CookieNotFound [Error]: Cannot complete OAuth process

### ISSUE THREAD

**Issue by ToyboxZach** [Shopify/shopify-node-api#223]
I am hitting this error

W20210726-11:57:09.341(-7)? (STDERR) Error with shopify auth callback CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: test-toybox.myshopify.com
W20210726-11:57:09.342(-7)? (STDERR)     at CookieNotFound.ShopifyError [as constructor] (/Users/zacholigschlaeger/toybox/node_modules/@shopify/shopify-api/dist/error.js:13:28)

Whenever I try to open my app within the Shopify admin console. I have tested it and my extension code is able to run and be authenticated but I cannot get it to work if I am inside of the shopify admin page context

My code is pretty close to the example code in this directory. Not sure what else I could be missing.

```
Shopify.Context.initialize({
  API_KEY: settings?.API_KEY ?? "",
  API_SECRET_KEY: settings?.API_SECRET ?? "",
  HOST_NAME: MY_HOST_NAME
  SCOPES: [
    // Add scope strings as needed, you can use AdminApiScopes exported from this library like so
    "write_products",
    "read_customer_payment_methods",
    "read_own_subscription_contracts",
    "write_own_subscription_contracts",
    "read_orders",
  ],
  IS_EMBEDDED_APP: true,

  API_VERSION: ApiVersion.July21,
});


WebApp.connectHandlers.use("/validate-shopify", async function (request: npm$connect$IncomingMessage, response, next) {
  try {
    const authRoute = await Shopify.Auth.beginAuth(
      request,
      response,
      request.query.shop,
      "/shopify/auth/callback",
      true
    );
    response.writeHead(302, {
      Location: authRoute,
    });
    response.end();
  } catch (e) {
    console.error("Error with shopify auth callback", e);
    if (e instanceof Shopify.Errors.ShopifyError) {
      response.end(e.message);
    } else {
      response.end(`Failed to start OAuth process: ${e.message}`);
    }
    return;
  }
});

WebApp.connectHandlers.use("/shopify/auth/callback", async function (request: npm$connect$IncomingMessage, response) {
  try {
    await Shopify.Auth.validateAuthCallback(request, response, request.query);
    response.writeHead(302, {
      Location: `https://${request.query.shop}/admin/apps/play-packs`,
    });
    response.end();
  } catch (e) {
    console.error("Error with shopify auth callback", e);
    if (e instanceof Shopify.Errors.ShopifyError) {
      response.end(e.message);
    } else {
      response.end(`Failed to complete OAuth process: ${e.message}`);
    }
    return;
  }
});
```

**Comment by mr-moto** [comment]
@ToyboxZach were you able to figure out a solution?

**Comment by ToyboxZach** [comment]
Is there any status on this issue?  It is still broken even on the latest version

**Comment by ckypper** [comment]
![image](https://user-images.githubusercontent.com/33152373/140603282-de8019f5-c876-420f-ac2d-c991d84977cf.png)
Any update on this? 
validateAuthCallback alway failed with error: Cannot complete OAuth process. Could not find an OAuth cookie for shop url

**Comment by ToyboxZach** [comment]
This problem ended up being that I didn't set up a subscription link extension on my Shopify app. That was making it so I wasn't going to the right url for the case I needed which started to break this down.

**Comment by Skriptach** [comment]
So how to fix it?
