### ISSUE TITLE
Error details not accessible for HTTP client

### ISSUE THREAD

**Issue by Boxonical** [Shopify/shopify-node-api#237]
# Issue summary

Shopify error code / details are not accessible in the .catch() method of HTTP clients, making debugging difficult & error handling impossible.

Sample HTTP response from Shopify:
```json
{
  "errors": {
    "line_items": [
      "must have at least one line item"
    ]
  }
}
```

The error object in .catch():
```json
{
    "message": "Received an error response (422 Unprocessable Entity) from Shopify: [object Object]. If you report this error, please include this id: 250f9792-8c43-4993-85e7-14c9659061a4",
    "code": 422,
    "statusText": "Unprocessable Entity"
}
```

## Expected behavior

Perhaps a more meaningful error:
```json
{
  "message": "Received an error response (422 Unprocessable Entity) from Shopify: [object Object]. If you report this error, please include this id: 250f9792-8c43-4993-85e7-14c9659061a4",
  "code": 422,
  "statusText": "Unprocessable Entity",
  "details": {
    "line_items": [
      "must have at least one line item"
    ]
  }
}
```

## Actual behavior

`[object Object]` in error message comes from:
https://github.com/Shopify/shopify-node-api/blob/0ee4f8adb6260b552d447b8e03d8f34067a34e9a/src/clients/http_client/http_client.ts#L236-L238

Error thrown here:
https://github.com/Shopify/shopify-node-api/blob/0ee4f8adb6260b552d447b8e03d8f34067a34e9a/src/clients/http_client/http_client.ts#L251-L256

## Steps to reproduce the problem

```javascript
const { Shopify } = require('@shopify/shopify-api'),
	DOMAIN = '',
	API_KEY = '',
	API_SECRET_KEY = '',
	ACCESS_TOKEN = ''

Shopify.Context.initialize({
	API_KEY,
	API_SECRET_KEY,
	SCOPES: ['write_orders'],
	HOST_NAME: 'localhost',
	IS_EMBEDDED_APP: false,
	IS_PRIVATE_APP: false,
	API_VERSION: '2021-07'
})

const client = new Shopify.Clients.Rest(DOMAIN, ACCESS_TOKEN)
client.post({
	path: 'orders',
	type: 'application/json',
	data: {
		order: {
			line_items: []
		}
	}
})
	.then(res => {
		console.log('res', res)
	})
	.catch(err => {
		// {
		//     "message": "Received an error response (422 Unprocessable Entity) from Shopify: [object Object]. If you report this error, please include this id: 250f9792-8c43-4993-85e7-14c9659061a4",
		//     "code": 422,
		//     "statusText": "Unprocessable Entity"
		// }
		console.log('err', err)
	})
```

**Comment by paulomarg** [comment]
Hey @Boxonical, thanks for the very detailed issue! You raise a good point, we'll look into making that error information available in the response.

**Comment by customerhub** [comment]
Try looking at the response body in the catch error - like this:
`try {
   await shopify.product.create(productData)
} catch (error) {
  console.log(error.response.body);
}`
That will show you the more detailed error from Shopify.

**Comment by ferares** [comment]
@customerhub that works! is that included in the docs somewhere?
