### ISSUE TITLE
loadCurrentSession when returning to an installed app

### ISSUE THREAD

**Issue by artooras** [Shopify/shopify-node-api#251]
# Issue summary

`Shopify.Auth.loadCurrentSession()` fails to load a session when opening an already installed app.

## Expected behavior

An offline session should be retrieved.

## Actual behavior

No session is found.

## Steps to reproduce the problem

1. Install the app using the steps described in the documentation for this library while using `CustomSessionStorage` (`beginAuth`, `validateAuthCallback`, save offline session to DB, etc.). All this happens successfully, I have a record in the DB for `offline_mystore.myshopify.com` with `accessToken`, etc.
1. On the shop, go back to the list of Apps and open the recently installed app again.
1. The `loadCurrentSession` function on my app entry route fails to find an active session, so instead it overwrites the session entry in my DB with a temporary one (without the access token).

The query parameters for the app entry route when opening the app for the first time (to install) are `hmac`, `shop` and `timestamp`. When opening the app the second time (after it has been installed), the parameters are `hmac`, `host`, `locale`, `session`, `shop` and `timestamp`. And the call to load the session is `const session = await Shopify.Utils.loadCurrentSession(req, res, false)`, i.e. I want to find an offline session.

I could, of course, try to query my DB for `'offline_' + req.query.shop`, but this feels very hacky...

Perhaps I'm just misunderstanding how sessions need to be looked up?

**Comment by rodrigograca31** [comment]
@artooras where do you get `shop` from tho?
Do you always pass it in the URL and do `ctx.query.shop` ? 🤔
