### ISSUE TITLE
AuthScope.equals cannot compare SCOPES as it is supposed to do

### ISSUE THREAD

**Issue by denik1981** [Shopify/shopify-node-api#254]
# Issue summary

Following the docs (below) I should be able to compare a chage on my access scope by using a utility lib (AuthScope)
https://github.com/Shopify/shopify-node-api/blob/main/docs/usage/oauth.md#detecting-scope-changes ↓

I have check the little utility tool and seems to be comparing things that are structure completely different. The uitility is using Sets to simplify he comparisson but the Set used to work with are wrongly built. Instead of having a Set of the different scopes provided the utility does unexpected and converted all scopes into a Set of only ONE long string. So then the comparisson fails Set.has(x) of course ends up failing. 

## Expected behavior

As the **documentation** 

## Actual behavior

The current problem is that the little snippet that should react to a change in scope is evaluated as **true** always so you are sending the user back to Oauth every single time.

**Comment by bishpls** [comment]
Was this silently fixed? I'm unable to reproduce the issue on Version 2.0.0 of the API; calling Shopify.SCOPES.equals("{sessionScopes}") works properly so far as I can tell. Are you passing in a comma-separated string of scopes to .equals()?

**Comment by denik1981** [comment]
@bishpls This was reported 3 months ago. It might have changed/solved now and I frankly don't remember quite well the source of the issue. I will close this.
