### ISSUE TITLE
Mandantory GDPR webhooks

### ISSUE THREAD

**Issue by cmnstmntmn** [Shopify/shopify-node-api#256]
There is no easy way to find the topic for a mandatory web-hook;

From documentations the list of these 3 mandantory webhooks is:

**list 1**:
* **customers/data_request**: Requests to view stored customer data
* **customers/redact**: Requests deletion of customer data
* **shop/redact**: Requests deletion of shop data

however, all examples includes **APP_UNINSTALLED** but there is no example with the other three.

My question so far.. 
Is there a correlation between `list 1` and this list https://shopify.dev/api/admin-graphql/2021-10/enums/webhooksubscriptiontopic ?

**Comment by bishpls** [comment]
Adding onto this issue: something else missing from the documentation is guidance on verifying that the mandatory GDPR webhooks come from Shopify. 

The official docs include examples in Ruby, PHP, and Python here: https://shopify.dev/apps/webhooks/configuration/https#verify-the-webhook

but since these webhooks don't go through Shopify.Webhooks.Registry.process (which is handling the hmac validation to confirm the requests are, in fact, coming from Shopify), it would be very useful to have an official example of manually going through the hmac validation process to verify the webhooks! (Or, even better, an invokable util function we can use to do so)

If I'm understanding the process correctly, validating general requests / oAuth functions a little differently from validating webhooks, which is why Registry.process doesn't use hmac-validator.ts; is it best practice at present to essentially repackage the relevant code from Registry.process for mandatory GDPR webhooks?

**Comment by TheSecurityDev** [comment]
@bishpls Dude you're a life saver. I literally needed to know this exact thing, since handling the mandatory webhooks seems different than using the normal `Shopify.Webhooks.Registry.process()` method, and I find this thread with your reply just 3 hours old!

I think something as important and common as this should be handled by the library in some way. I don't know why we can't just use the normal webhook handler functions for this :/

And yes, this whole thing needs much more documentation, and there needs to be a way to test the webhooks functionality beforehand since every app needs to handle these webhooks.

**Comment by bishpls** [comment]
You can test the customers/data endpoint quite easily! 

Assuming your app is installed on a development store you have access to, navigate to Customers > click any Customer > check the right panel for the "Customer Privacy" block; 'View customer data' will immediately send a payload to the customers/data endpoint set up for your installed app(s). "Erase Personal Data" hits the customers/redact endpoint, but is subject to the delay of ten-days-or-six-months, so it's not particularly useful for testing. 

![Screen Shot 2022-01-21 at 8 41 34 PM](https://user-images.githubusercontent.com/41241382/150619792-b1b579af-d919-4724-8039-b694be7f5dfc.png)

**Comment by bishpls** [comment]
HOWEVER it's worth calling attention (yet again) to the fact that body-parser / express.json breaks the standard Shopify.Webhooks.Registry.process function, so if you're using either to parse the payload from the GDPR webhooks, you'll either want to run app.use(express.json()) AFTER /webhooks but before the GDPR routes, or just inline as a substack call for the GDPR routes. 

I've set mine up via the latter, like so:

```
api.post('/customers/redact', express.json(), verifyWebhookRequest, async(req, res) => {
  res.status(200).send();
  // Business logic goes here
}
```

**Comment by TheSecurityDev** [comment]
@bishpls Just a suggestion, I would change `process.env.SHOPIFY_API_SECRET_KEY` to `Shopify.Context.API_SECRET_KEY`, so it always works, no matter the env variable name.

**Comment by akeans-mgs** [comment]
Our app was rejected by Shopify's automated submission test immediately after submission with the same reason of

> App must verify the authenticity of the request from Shopify.
> Expected HTTP 401 (Unauthorized), but got HTTP 405 from https://8235cf20c428.ngrok.io/webhook/gdpr/shop_redact. Your app's HTTPS webhook endpoints must validate the HMAC digest of each request, and return an HTTP 401 (Unauthorized) response when rejecting a request that has an invalid digest.

Error I received

```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined in
at Hmac.update (internal/crypto/hash.js:84:11)
at receiveWebhookMiddleware( \node_modules@shopify\koa-shopify-webhooks\build\cjs\receive.js:32:63 )
at dispatch( \node_modules@shopify\koa-shopify-webhooks\node_modules\koa-compose\index.js:42:32 )
at bodyParser \node_modules\koa-bodyparser\index.js:95:11)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at \node_modules\koa-mount\index.js:58:5
```

You can check the code here.
https://github.com/akeans-mgs/mgs_testing

refer the line [ https://github.com/akeans-mgs/mgs_testing/blob/main/server/server.js#L85 ]( https://github.com/akeans-mgs/mgs_testing/blob/main/server/server.js#L85)

**Comment by stephenkeable** [comment]
> hey @stephenkeable it doesn't seem like the function defines neither `req` nor `ShopifyHeader`

Yeh it assumes some globals from the `server/server.js` file. You could change the signature to pass these in instead, so:
`function verifyWebhookRequest(body, req) { ... }`
Or something similar

**Comment by stephenkeable** [comment]
@akeans-mgs sorry in my solution I haven't used `koa-shopify-webhooks` you might find some help for that in the https://github.com/Shopify/quilt issues

**Comment by akeans-mgs** [comment]
@stephenkeable 
If possible share some code to integrate Shopify GDPR webhook in Node + React.

**Comment by swherden** [comment]
@stephenkeable you can use receiveWebhook method from @shopify/koa-shopify-webhooks. 
Example code from my Koa server - maybe it is of value for you: 
```
import { receiveWebhook } from '@shopify/koa-shopify-webhooks';
...
const webhook = receiveWebhook({ secret: SHOPIFY_API_SECRET });
router.post(
        <enter your webhook path e.g /webhooks/gdpr/customerdatarequest>,
        webhook,
        (ctx: any) => {
            console.log(ctx.request);
            const { shop_domain, topic, payload } = getWebhookConfig(ctx);
            console.log(shop_domain, topic, payload);
           //do important GDPR things here
        }
    );
...
function getWebhookConfig(ctx: any) {
    const shop_domain = ctx.state.webhook.domain;
    const topic = ctx.state.webhook.topic;
    const payload = ctx.state.webhook.payload;
    return { shop_domain, topic, payload };
}
```

**Comment by daviareias** [comment]
Thanks guys, the following code worked for me (you can erase the console.logs later, I've added it just to understand how it works):

```
function verifyWebhookRequest(body,req) {

    try {
      const generatedHash = crypto
        .createHmac("SHA256", Shopify.Context.API_SECRET_KEY)
        .update(JSON.stringify(body), "utf8")
        .digest("base64");
      const ShopifyHeader = 'x-shopify-hmac-sha256';
      const hmac = req.get(ShopifyHeader); // Equal to 'X-Shopify-Hmac-Sha256' at time of coding
      const safeCompareResult = Shopify.Utils.safeCompare(generatedHash, hmac);

      if (!!safeCompareResult) {
        console.log('Safe')
        return true;
      } else {
        console.log('Not Safe')
        return false;
      }
    } catch (error) {
      console.log('error', error)
      return false;
    }
 }

router.post("/customers/data_request", koaBody(), (ctx) => {
  if (verifyWebhookRequest(ctx.request.body,ctx.request) === true) {
    console.log('verified :)')
    ctx.res.statusCode = 200;
// do something with the ctx.request.body
  } else {
    console.log('Not verified')
    ctx.res.statusCode = 401;
  }
});
```

**Comment by akeans-mgs** [comment]
@swherden 
Thanks for replying. Kindly accept my request.

I have invited you to [my sample shopify app repo](https://github.com/akeans-mgs/mgs_testing) , kindly accept it. And we can do the needful to work with GDPR Webhook Integration.

**Comment by yashsony** [comment]
Just one add on to this conversation 
You don't create webhook subscriptions to [mandatory webhooks](https://shopify.dev/apps/webhooks/configuration/mandatory-webhooks). Instead, you configure mandatory webhooks in your Partner Dashboard as part of your app setup.
You just need to define endpoint of mandatory webhook.

**Comment by Ankita-K-Chauhan** [comment]
My response is not working for mandatory webhook any suggestion .

**Comment by i-moreno** [comment]
My 2 cents to this issue:

1. Add endpoint routes in your app dashboard as @arfanliaqat mentions
2. I create a file to handle gdpr webhooks routes
3. Add your middleware to verify the HMAC
4. Update your server file, **make sure to call express json before grpr routes.**

### gdpr webhooks routes
`
import express from "express";
import {
  customerDataRequest,
  customerRedact,
  shopRedact,
} from "../webhooks/gdpr.js";

const gdprRoutes = express.Router();

gdprRoutes.post("/:topic", async (req, res) => {
  const { body } = req;
  const { topic } = req.params;
  const shop = req.body.shop_domain;

  let response;

  switch (topic) {
    case "customers_data_request":
      response = await customerDataRequest(topic, shop, body);
      break;
    case "customers_redact":
      response = await customerRedact(topic, shop, body);
      break;
    case "shop_redact":
      response = await shopRedact(topic, shop, body);
      break;
    default:
      console.log("--> Unidentified GDPR Topic");
      break;
  }

  if (response && response.success) {
    res.status(200).send();
  } else {
    res.status(400).send("Error with mandatory GDPR webhooks");
  }
});

export default gdprRoutes;
`

### HMAC middleware verification

```
import crypto from "crypto";
import { Shopify } from "@shopify/shopify-api";

export const hmacVerify = (req, res, next) => {
  try {
    const generateHash = crypto
      .createHmac("SHA256", process.env.SHOPIFY_API_SECRET)
      .update(JSON.stringify(req.body), "utf8")
      .digest("base64");

    const hmac = req.headers["x-shopify-hmac-sha256"];

    if (Shopify.Utils.safeCompare(generateHash, hmac)) {
      console.log("HMAC successfully verified for webhook route.");
      next();
    } else {
      console.log("Shopify hmac verification for webhook failed, aborting.");
      return res.status(401).send();
    }
  } catch (error) {
    console.log("--> HMAC ERROR", error);
  }
};
```


### Server extract
```
  app.use(express.json());
  app.use("/gdpr", hmacVerify, gdprRoutes);
```

**Comment by mkevinosullivan** [comment]
@olivierbouchard To set up the `/api/webhooks` endpoint: https://github.com/Shopify/shopify-app-template-node/blob/cli_three/web/index.js#L79-L93

```javascript
  // Do not call app.use(express.json()) before processing webhooks with
  // Shopify.Webhooks.Registry.process().
  // See https://github.com/Shopify/shopify-api-node/blob/main/docs/usage/webhooks.md#note-regarding-use-of-body-parsers
  // for more details.
  app.post("/api/webhooks", async (req, res) => {
    try {
      await Shopify.Webhooks.Registry.process(req, res);
      console.log(`Webhook processed, returned status code 200`);
    } catch (e) {
      console.log(`Failed to process webhook: ${e.message}`);
      if (!res.headersSent) {
        res.status(500).send(e.message);
      }
    }
  });
```


> what are the URLs you write in the app setup?

I'm not sure what you mean by this.

**Comment by mkevinosullivan** [comment]
Oh, do you mean the App Setup in your Partner Dashboard?
![Screen Shot 2022-10-17 at 11 08 23 AM](https://user-images.githubusercontent.com/56687600/196214309-355ef99c-b55b-47e8-b88b-3bc8d642af21.png)

For these, it should be your App URL (same as configured at the top of the App Setup page), followed by `/api/webhooks`, e.g.,
`https://<app host name>/api/webhooks`

**Comment by olivierbouchard** [comment]
@mkevinosullivan So you just fill the 3 spaces with `https://<app host name>/api/webhooks` and it supposed to work? You have nothing else to add in your code?

**Comment by mkevinosullivan** [comment]
You'll need to modify the `gdpr.js` file with actual code to deal with the three GDPR scenarios as they apply to your specific app, but as far as the webhooks being triggered, that should work once you populate those three fields.

**Comment by ifat420** [comment]
> Oh, do you mean the App Setup in your Partner Dashboard? ![Screen Shot 2022-10-17 at 11 08 23 AM](https://user-images.githubusercontent.com/56687600/196214309-355ef99c-b55b-47e8-b88b-3bc8d642af21.png)
> 
> For these, it should be your App URL (same as configured at the top of the App Setup page), followed by `/api/webhooks`, e.g., `https://<app host name>/api/webhooks`

Hey @mkevinosullivan . I have a question should I input the same URL on those three input boxes?

Ex:

Customer data request endpoint:
`example: https://example.com/api/webhooks`

Customer data erasure endpoint
`example: https://example.com/api/webhooks`

Shop data erasure endpoint
`example: https://example.com/api/webhooks`

**Comment by ifat420** [comment]
> > > Oh, do you mean the App Setup in your Partner Dashboard? ![Screen Shot 2022-10-17 at 11 08 23 AM](https://user-images.githubusercontent.com/56687600/196214309-355ef99c-b55b-47e8-b88b-3bc8d642af21.png)
> > > For these, it should be your App URL (same as configured at the top of the App Setup page), followed by `/api/webhooks`, e.g., `https://<app host name>/api/webhooks`
> > 
> > 
> > Hey @mkevinosullivan . I have a question should I input the same URL on those three input boxes?
> > Ex:
> > Customer data request endpoint: `example: https://example.com/api/webhooks`
> > Customer data erasure endpoint `example: https://example.com/api/webhooks`
> > Shop data erasure endpoint `example: https://example.com/api/webhooks`
> 
> yes enter the same URL & you need to manage the type of webhook inside the business logic.

Hey @adventuretocode ! 
![image](https://user-images.githubusercontent.com/12673582/205072528-86228d63-8e97-4b25-a1bc-ed21ca5dd852.png)

Do I need to return any status code from here ?

**Comment by adventuretocode** [comment]
@arfanliaqat   yes first you need to do the GDPR action clean up the relevant data from your app, 
then you need return then status code 200 else unauthorised return the 401

**Comment by ifat420** [comment]
> @arfanliaqat yes first you need to do the GDPR action clean up the relevant data from your app, then you need return then status code 200 else unauthorised return the 401

But here is no `res` parameter webhookHandler function ?

Can you please show me a example code @adventuretocode ?

**Comment by adventuretocode** [comment]
> > @arfanliaqat yes first you need to do the GDPR action clean up the relevant data from your app, then you need return then status code 200 else unauthorised return the 401
> 
> But here is no `res` parameter webhookHandler function ?
> 
> Can you please show me a example code @adventuretocode ?

you need to return the flag then main webhook ther is req. object .  which code repo you referring ?

**Comment by dongido001** [comment]
@ifat420 how did you later fix this ? The cli 3 template does not pass verification because it does not return 401 for invalid hmac

**Comment by ifat420** [comment]
Hello, @dongido001  Shopify node CLI node is bullshit so I switch to another template.

**Comment by ahkjxy** [comment]
> > Oh, do you mean the App Setup in your Partner Dashboard? ![Screen Shot 2022-10-17 at 11 08 23 AM](https://user-images.githubusercontent.com/56687600/196214309-355ef99c-b55b-47e8-b88b-3bc8d642af21.png)
> > For these, it should be your App URL (same as configured at the top of the App Setup page), followed by `/api/webhooks`, e.g., `https://<app host name>/api/webhooks`
> 
> Hey @mkevinosullivan . I have a question should I input the same URL on those three input boxes?
> 
> Ex:
> 
> Customer data request endpoint: `example: https://example.com/api/webhooks`
> 
> Customer data erasure endpoint `example: https://example.com/api/webhooks`
> 
> Shop data erasure endpoint `example: https://example.com/api/webhooks`

你好，你的这个问题解决了吗？有没有可以用的server.js文件可以参考啊，谢谢！

**Comment by dani-sanomads** [comment]
@ahkjxy @dongido001 
filename: redirect-to-auth.js
async function serverSideRedirect(req, res, app) {
  const { headers } = req;
  if (!headers["x-shopify-shop-domain"] && !req?.query?.shop) {
    console.log("No SHop available : Headers[x-shopify-shop-domain]");
    // res.status(401);
    // return res.send("No shop provided");
  }

  try {
    const redirectUrl = await Shopify.Auth.beginAuth(
      req,
      res,
      req.query.shop,
      "/api/auth/callback",
      app.get("use-online-tokens")
    );
    return res.redirect(redirectUrl);
  } catch (error) {
    console.log("serverSideRedirect Error =>", error);
    res.status(401);
    return res.send("No shop provided");
  }
}

Worked for me due to an issue in the v5 shopify/api. I would recommend to use the v6 package.

**Comment by dani-sanomads** [comment]
Add middleware to each post request for Webhooks to validate the hmac.
