### ISSUE TITLE
Update documentation for setting up webhooks

### ISSUE THREAD

**Issue by TheSecurityDev** [Shopify/shopify-node-api#262]
## Overview/summary

The documentation [here](https://github.com/Shopify/shopify-node-api/blob/main/docs/usage/webhooks.md#register-a-webhook) on how to set up webhooks is no longer accurate after v2 of the library was released. It should be updated to reflect the new changes as to how webhooks are registered.

I was able to get it working using the following code:

**On app startup after context initilization:**
```typescript
// Initialize the webhook handlers that we will be using
const WEBHOOKS_REGISTRY = {
  APP_UNINSTALLED: {
    path: "/webhooks",
    webhookHandler: async (topic: string, shop: string, body: string) => {
      await onAppUninstalled(shop, body);
    },
  },
};
// Add the webhook handlers to the registry
Shopify.Webhooks.Registry.addHandlers(WEBHOOKS_REGISTRY);
```

**To add the webhooks for a shop:**
```typescript
// Register all the initilized handlers on this shop
await Shopify.Webhooks.Registry.registerAll({ shop, accessToken });
```

And I'm not sure, but I'm assuming you still have to call `registerAll` for every shop on startup, as well as when a shop is installed.

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Hey @TheSecurityDev, thank you for pointing that out, we'll update the docs!

I believe your solution is the correct one - you can add your handlers at any point before calling the `process` method, and you only need to do it once when your app starts up, so doing it while setting up `Context` is what we recommend as well.

You do need to register the webhooks for each shop after OAuth, but you don't need to re-add them when your app starts up - only when a shop installs the app, or when you want to add more webhooks to a pre-installed shop. The reason for that sentence in the docs was that we were previously setting the handlers at registration time, which is the main change we made when we moved to v2.

Hope this helps!
