### ISSUE TITLE
Error: Context has not been properly initialized. Please call the .initialize() method to setup your app context object.

### ISSUE THREAD

**Issue by conspireagency** [Shopify/shopify-node-api#264]
# Issue summary

Upgraded to @shopify/shopify-api 2.0.0 and @shopify/koa-shopify-auth 4.1.2.

## Actual behavior

In server.js ShopifyContext is being initialized as typically done, however upon visiting the application route it throws an error that Context has not been properly initialized.  Logging the Context shows that it is indeed initialized.

`Shopify.Context.initialize({
  API_KEY: process.env.SHOPIFY_API_KEY,
  API_SECRET_KEY: process.env.SHOPIFY_API_SECRET,
  SCOPES: process.env.SCOPES.split(","),
  HOST_NAME: process.env.HOST.replace(/https:\/\//, ""),
  API_VERSION: ApiVersion.October21,
  IS_EMBEDDED_APP: true,
  IS_PRIVATE_APP: false,
  // This should be replaced with your preferred storage strategy
  SESSION_STORAGE: new Shopify.Session.CustomSessionStorage(
    storeCallback,
    loadCallback,
    deleteCallback
  ),
});`

Currently trying to track down the problem looking at updates to the repos for both packages, granted the app was working fine before upgrading.

Things I noticed so far in my detective work:
-New documentation for @koa-shopify-auth mentions using shopifyAuth() instead of createShopifyAuth().  However, if you generate a new skeleton app project via the CLI with 4.1.2 it uses the old createShopifyAuth().  Using either one doesn't seem to make a difference.

## Background
App was generated using the CLI.  Not much has changed in server.js besides switching to a CustomSessionStorage using a database.  App was working prior to update.  Wanted to update as @shopify/shopify-api seems to be rapidly rolling out bugfixes.  One the ones being when I discovered webhook registry was taking place in memory causing webhooks to fail on server restart (implemented a fix but yeah) =P

**Comment by conspireagency** [comment]
Realized that koa-shopify-auth has shopify-api as a dependency already.  Was due to some sort of conflict.

**Comment by limeforadime** [comment]
> Realized that koa-shopify-auth has shopify-api as a dependency already. Was due to some sort of conflict.

Yeah I saw in another thread that they actually plan on deprecating koa-shopify-auth soon as most of it's functionality is now included in the official shopify-api package.

**Comment by conspireagency** [comment]
We just ended up getting rid of koa-shopify-auth completely in favor of the new 2.0 version of shopify-api.  After coming back with fresh eyes it was only ~30-1hr to swap it out =). @limeforadime

**Comment by limeforadime** [comment]
Cool! Glad to hear it's an easy fix, because I was actually going to switch over to the shopify-api solution as well.

**Comment by limeforadime** [comment]
> We just ended up getting rid of koa-shopify-auth completely in favor of the new 2.0 version of shopify-api. After coming back with fresh eyes it was only ~30-1hr to swap it out =). @limeforadime

I'm actually having a heck of a time getting the shopify-api auth methods to work. I keep getting Oauth Cookie errors. Could I bother you and ask to see the code for your auth routes? The `/auth` and `/auth/callback` routes in particular. Following the Oauth documentation for shopify-node-api didn't work at all for me.

**Comment by aurnik** [comment]
@conspireagency @limeforadime Hey I'm trying to get rid of koa-shopify-auth as well, could either of you share more on what you had to do to swap it out?

These are the two routes for me:
```node
router.get("/auth", async (ctx) => {
    let authRoute = await Shopify.Auth.beginAuth(
      ctx.req,
      ctx.res,
      ctx.query.shop,
      "/auth/callback",
      true
    );
    return ctx.redirect(authRoute);
  });
  router.get("/auth/callback", async (ctx) => {
    try {
      const session = await Shopify.Auth.validateAuthCallback(
        ctx.req,
        ctx.res,
        ctx.query
      );
      ACTIVE_SHOPIFY_SHOPS[SHOP] = session.scope;

      const { accessToken } = session;

    } catch (error) {
      console.error(error);
    }
    return ctx.redirect(`/?host=${ctx.query.host}&shop=${ctx.query.shop}`);
  });
```
but it leads to a "CookieNotFound [Error]"

**Comment by limeforadime** [comment]
@aurnik Currently in the process of fixing mine, had some trouble but I think I hit a breakthrough. Will update you when I get it working.

**Comment by limeforadime** [comment]
It was an ugly fix but after reading the breaking changes introduced by [#253](https://github.com/Shopify/shopify-node-api/pull/253) I fixed this by forking my own version of koa-shopify-auth and isolating the part that broke with the shopify-api v2.0 update and changing it from this:
```js
// koa-shopify-auth -> src/auth/index.ts, line 97
await Shopify.Auth.validateAuthCallback(ctx.req, ctx.res, ctx.query);
ctx.state.shopify = await Shopify.Utils.loadCurrentSession(ctx.req, ctx.res, config.accessMode === 'online');
```
to this:
```js
const session = await Shopify.Auth.validateAuthCallback(ctx.req, ctx.res, ctx.query);
ctx.state.shopify = session;
```

Koa-shopify-auth has functions that assist with dealing with top level redirects vs inline redirects for embedded apps, which I wasn't able to get working with just the shopify-api package alone. In fact koa-shopify-auth is built upon shopify-api so it made more sense to me to keep on using it.

**Comment by amey-acharya** [comment]
I'm actually using the instructions Shopify has given [here](https://github.com/shopify/shopify_app#introduction).
I'm trying to make a rails app but always get this error once I enter the shop URL. Is there any fix to this?
I have used the gem Figaro to save the Shopify API and secrets.

<img width="952" alt="Screenshot 2022-05-20 at 1 30 05 AM" src="https://user-images.githubusercontent.com/89564504/169394778-b91b92b2-bfb0-4f66-b7e6-472dcec126c1.png">

**I seem to be getting an internal server error 500**




`Started POST "/login" for 127.0.0.1 at 2022-05-20 01:25:48 +0530
Processing by ShopifyApp::SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "shop"=>"hyperr-delivery.myshopify.com"}
  Rendering /Users/ameyacharya/.rvm/gems/ruby-3.0.0/gems/shopify_app-19.0.2/app/views/shopify_app/shared/redirect.html.erb
  Rendered /Users/ameyacharya/.rvm/gems/ruby-3.0.0/gems/shopify_app-19.0.2/app/views/shopify_app/shared/redirect.html.erb (Duration: 61.8ms | Allocations: 31728)
Completed 200 OK in 64ms (Views: 62.7ms | ActiveRecord: 0.0ms | Allocations: 32578)


Started GET "/login?shop=hyperr-delivery.myshopify.com&top_level=true" for 127.0.0.1 at 2022-05-20 01:25:48 +0530
Processing by ShopifyApp::SessionsController#new as HTML
  Parameters: {"shop"=>"hyperr-delivery.myshopify.com", "top_level"=>"true"}
  Shop Load (0.5ms)  SELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = ? LIMIT ?  [["shopify_domain", "hyperr-delivery.myshopify.com"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.7ms | Allocations: 6618)



ShopifyAPI::Errors::ContextNotSetupError (ShopifyAPI::Context not setup, please call ShopifyAPI::Context.setup):
  
shopify_api (10.1.0) lib/shopify_api/auth/oauth.rb:23:in `begin_auth'
sorbet-runtime (0.5.10020) lib/types/private/methods/call_validation.rb:161:in `bind_call'
sorbet-runtime (0.5.10020) lib/types/private/methods/call_validation.rb:161:in `validate_call'
sorbet-runtime (0.5.10020) lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
shopify_app (19.0.2) app/controllers/shopify_app/sessions_controller.rb:47:in `start_oauth'
shopify_app (19.0.2) app/controllers/shopify_app/sessions_controller.rb:40:in `authenticate'
shopify_app (19.0.2) app/controllers/shopify_app/sessions_controller.rb:14:in `new'
actionpack (7.0.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.3) lib/abstract_controller/base.rb:215:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.3) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.3) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.3) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.3) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.3) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.3) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.3) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
railties (7.0.3) lib/rails/engine.rb:530:in `call'
railties (7.0.3) lib/rails/railtie.rb:226:in `public_send'
railties (7.0.3) lib/rails/railtie.rb:226:in `method_missing'
actionpack (7.0.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (7.0.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/cookies.rb:697:in `call'
activerecord (7.0.3) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.3) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.3) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `block in tagged'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:38:in `tagged'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `tagged'
railties (7.0.3) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
shopify_app (19.0.2) lib/shopify_app/middleware/jwt_middleware.rb:24:in `call_next'
shopify_app (19.0.2) lib/shopify_app/middleware/jwt_middleware.rb:12:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.3) lib/rails/engine.rb:530:in `call'
puma (5.6.4) lib/puma/configuration.rb:252:in `call'
puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
puma (5.6.4) lib/puma/server.rb:441:in `process_client'
puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

`

**Comment by conspireagency** [comment]
@limeforadime @aurnik late response here, but I scrapped the koa library completely and just used the framework independent latest version of shopify api.  If you look at the library itself (outside of node modules) it's very cleanly written, was able to modify to support multiple public apps in a single codebase and more.  10/10 recommend going this route.

**Comment by gsaranya256** [comment]
Hi am using "@shopify/koa-shopify-auth": "^5.0.3" and am getting this error when I start the server, is there any fix


/Shopify/Development/Shopify_Twilio/server/server.js:40
_shopifyApi["default"].Context.initialize({
                       ^

TypeError: Cannot read properties of undefined (reading 'Context')
    at Object.<anonymous> (/Shopify/Development/Shopify_Twilio/server/server.js:35:9)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._compile (/Shopify/Development/Shopify_Twilio/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Object.newLoader [as .js] (/Shopify/Development/Shopify_Twilio/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Shopify/Development/Shopify_Twilio/server/index.js:7:18)

Node.js v20.3.0
[nodemon] app crashed - waiting for file changes before starting...
