### ISSUE TITLE
ApolloClient 'Access denied for giftCards field'

### ISSUE THREAD

**Issue by nacmonad** [Shopify/shopify-node-api#271]
# Issue summary

Shopify-cli create app scope has 'read_gift_cards'/'write_gift_cards'.
Node Api Context set to ApiVersion.April21 (21-04).

`const gqlClient = new Shopify.Clients.Graphql('sonity-ltd.myshopify.com', TEST_ACCESS_TOKEN);
    const data = await gqlClient.query({
      data: {
        "query": query getGiftCards {
          giftCards(first: 10) {
            edges {
              node {
                id 
              }
            }
          }
        }
      },
    });
    const gc = data.body;
    console.log("gql client data ", gc)`

## Expected behavior

GraphQL query/mutation access as per https://shopify.dev/api/examples/gift-cards

## Actual behavior
Access denied for giftCards field.

## Steps to reproduce the problem
1) shopify-cli create private node app, serve to test store.
2) Run afforementioned query using @shopify-api/client.

**Comment by developerwok** [comment]
Leaving this answer behind for anyone who is attempting to interface with gift_cards

You need to have a Plus Account, and ask Shopify Support to enable it as well.
