### ISSUE TITLE
Price Rule Delete Error

### ISSUE THREAD

**Issue by xiddixaid** [Shopify/shopify-node-api#281]
# Issue summary

When I try to delete Price Rule with Admin API following the documentation mentioned over this link https://shopify.dev/api/admin-rest/2021-10/resources/pricerule#[delete]/admin/api/2021-10/price_rules/{price_rule_id}.json . It deletes my Price Rule from shopify but also through this error Failed to make Shopify HTTP request: FetchError: invalid json response body at https://example.myshopify.com/admin/api/2021-10/price_rules/1058298364037.json reason: Unexpected end of JSON input

## Expected behavior

Successful response after deletion of the Price Rule. 

## Actual behavior

Deletes the Price Rule from Shopify Store but also through invalid json error.

## Steps to reproduce the problem

1. Delete Price Rule with shopify-node-api (rest)

## Reduced test case

Properly handle JSON response data with shopify-node-api

**Comment by dek1chan** [comment]
I got same error on deleting recurring application charge.

**Comment by xiddixaid** [comment]
> I got same error on deleting recurring application charge.

Actually, this error occur when Shopify did not return any response and this app handling response with response.json(). According to Shopify Admin API REST its returns nothing 'No Content' on deletion of PriceRule and Coupon.


You can avoid this error by just making some changes to this file node_modules/@shopify/shopify-api/dist/clients/http_client/http_client.js.

replace 169 line : case 0: return [4 /*yield*/, response.json()]; 
with this line: case 0: return [4 /*yield*/, response.status !== 204 ? response.json() : response];

**Comment by umutsesen** [comment]
21 May, still not fixed. Do everyone has to waste 5 hours for just to learn this?
