### ISSUE TITLE
can not register GDPR webhooks 

### ISSUE THREAD

**Issue by redochka** [Shopify/shopify-node-api#290]
# Issue summary

Write a short description of the issue here ↓

```
const response = await Shopify.Webhooks.Registry.register({
        path : path,
        topic: "customers/data_request",
        accessToken,
        shop,
    });
```

error:

```
TypeError: Cannot read property 'webhookSubscriptions' of undefined
```

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://webkit.org/test-case-reduction/).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by kojo-shopify** [comment]
@redochka, unfortunately registering GDPR webhooks is not supported in this way. GDPR endpoints are considered mandatory webhooks for all public Shopify apps to subscribe to and need be specified in your app's configuration.

You can follow [this guide](https://shopify.dev/apps/webhooks/configuration/mandatory-webhooks#manage-endpoints-for-mandatory-webhooks) to register these endpoints through the App setup menu in your Partner Dashboard.

**Comment by redochka** [comment]
ok, however, can I still use the library to add the handler? 

```
Shopify.Webhooks.Registry.addHandler("customers/data_request", {
        webhookHandler: gdprHandler,
    })
```

Will the library work fine when the gdpr webhook is received?

**Comment by bishpls** [comment]
@redochka 

Nope!

You'll need to set up independent routes for handling the GDPR webhook requests, as well as run the validation for them. The process for doing so isn't in the documentation, especially as the [webhook documentation is out of date](https://github.com/Shopify/shopify-node-api/pull/276) and the Webhook verification process doesn't include Node examples in the dev docs; I've gone over a minimal example in the comments of [this issue](https://github.com/Shopify/shopify-node-api/issues/256), including accounting for a conflict with json.express() / bodyParser that it's very easy to run into.
