### ISSUE TITLE
Node React API Shopify  App Installation

### ISSUE THREAD

**Issue by shopify-development-code** [Shopify/shopify-node-api#304]
TypeError: Cannot read properties of undefined (reading 'map')
      at new AuthScopes (/var/www/html/productOptions/node_modules/@shopify/shopify-api/dist/auth/scopes/index.js:15:14)
      at AuthScopes.equals (/var/www/html/productOptions/node_modules/@shopify/shopify-api/dist/auth/scopes/index.js:40:21)
      at /var/www/html/productOptions/node_modules/@shopify/koa-shopify-auth/dist/src/verify-request/verify-token.js:24:79
      at step (/var/www/html/productOptions/node_modules/tslib/tslib.js:133:27)
      at Object.next (/var/www/html/productOptions/node_modules/tslib/tslib.js:114:57)
      at fulfilled (/var/www/html/productOptions/node_modules/tslib/tslib.js:104:62)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by limeforadime** [comment]
You'll probably need to provide a little more background/context than just a single error message.

**Comment by ismailalabou** [comment]
> There's not a lot of context provided but it might be there aren't any scopes being provided to the `Shopify.Context` during initialization, or not provided in the correct format. It should be either a comma-separated string (e.g., `'read_products, write_products'`) or an array of strings (e.g., `['read_products', 'write_products']`).

mine are like this:
![image](https://user-images.githubusercontent.com/28371448/191563815-2a5dc4bd-d120-4ec4-afeb-729db21b3680.png)

**Comment by ismailalabou** [comment]
and this is my frontend error message & devtool console errors:
![image](https://user-images.githubusercontent.com/28371448/191565396-7f5790c8-36ad-47e8-bd47-e4f4477dd7bb.png)
![image](https://user-images.githubusercontent.com/28371448/191565775-ee21d812-98d1-4ece-901b-6ed4a1fdd781.png)

**Comment by mkevinosullivan** [comment]
There's not enough information here, or background.

1. how was the app created?  (e.g. using the CLI, copying a template, ...?)
2. are you using the Shopify CLI to run the app during development?
3. for the console messages, what are the corresponding URLs, requests, responses that are causing those messages
4. how/when does the error occur?  please provide the steps that lead to this error.

For the given FE error message, what is the `shop=` parameter in the URL?

**Comment by ismailalabou** [comment]
> There's not enough information here, or background.
> 
> 1. how was the app created?  (e.g. using the CLI, copying a template, ...?)
> 2. are you using the Shopify CLI to run the app during development?
> 3. for the console messages, what are the corresponding URLs, requests, responses that are causing those messages
> 4. how/when does the error occur?  please provide the steps that lead to this error.
> 
> For the given FE error message, what is the `shop=` parameter in the URL?

1. using the cli (node)
2. no the app is hosted by Heroku, production.
4. when app first loads

the `shop=` parameter in the URL is the dev store i'm trying to test the app on

P.S: i'm using the old deprecated shopify app node template (next.js/koa.js)

**Comment by cquemin** [comment]
@ismailalabou Will you be able to migrate to v6 of the this library? I believe it could help solving your problem.  I will close this issue since you are using deprecated template. If it happens to you again with v6 of the `shopify-api-js` library, feel free to reopen this issue.
