### ISSUE TITLE
StoreFrontAccessToken Is not generated

### ISSUE THREAD

**Issue by TheCodingFreakj** [Shopify/shopify-node-api#375]
const adminApiClient = new Shopify.Clients.Rest(
        session.shop,
        session.accessToken
      );

      const storefrontTokenResponse = await adminApiClient.post({
        path: "storefront_access_tokens",
        type: 'application/json',
        data: {
          storefront_access_token: {
            title: "Test Title",
          },
        },
      });

I am writing this code to create storefront access token. But it does not seems to work.
this is something i am getting as response
Received an error response (403 Forbidden) from Shopify:
"Token must be eligible to manage storefront tokens."

I have attached all the access scopes.
Still i am unable to get this thing done.

Just want to confirm do i need to pass offline access token for this?
Any help would be much appreciated

**Comment by mkevinosullivan** [comment]
👋🏻  What access scopes has your app requested?

As can be noted on this [page](https://shopify.dev/api/admin-rest/2022-04/resources/storefrontaccesstoken#top)...
> If the app has not been granted any unauthenticated access scopes, then creating the storefront access token will fail.

**Comment by TheCodingFreakj** [comment]
@mkevinosullivan 

[
  'read_products',
  'write_themes',
  'read_orders',
  'write_orders',
  'write_content',
  'read_themes',
  'write_script_tags',
  'unauthenticated_read_content',
  'unauthenticated_read_checkouts',
  'unauthenticated_write_checkouts',
  'unauthenticated_read_customers',
  'unauthenticated_read_selling_plans',
  'unauthenticated_write_customers',
  'unauthenticated_read_customer_tags',
  'unauthenticated_read_product_tags',
  'unauthenticated_read_product_listings',
  'read_content',
  'write_content',
  'write_products',
  'write_customers',
  'read_customers',
  'write_draft_orders'
]

**Comment by TheCodingFreakj** [comment]
> > If the app has not been granted any unauthenticated access scopes, then creating the storefront access token will fail.


Have added all the unauthenticated access scopes

**Comment by mkevinosullivan** [comment]
@TheCodingFreakj I managed to replicate the error message, and was then able to obtain the StorefrontAccessToken by obtaining/using an OFFLINE token (i.e., set the fifth parameter (`isOnline?`) to `Shopify.Auth.beginAuth` to `false`.

Reference: https://community.shopify.com/c/shopify-apis-and-sdks/storefrontaccesstoken-request-quot-token-must-be-eligible-to/m-p/1403006/highlight/true#M74955
