### ISSUE TITLE
unable to deploy firebase function when importing v3.0.1 or later

### ISSUE THREAD

**Issue by zachsitka** [Shopify/shopify-node-api#388]
# Issue summary

When you import the @shopify/shopify-api package into a node firebase function, it will fail to deploy with the following error:
`Error: SQLITE_CANTOPEN: unable to open database file`

## Expected behavior

You should be able to deploy using this package.

## Actual behavior

When you deploy code that imports the @shopify/shopify-api package in a firebase function to the cloud, the function fails to deploy at the point where the function is invoked to make sure that it is properly deployed. When this happens, the function crashes with the error `Error: SQLITE_CANTOPEN: unable to open database file`.

This happens when using versions 3.0.1 or above. 3.0.0 is not affected and deploys fine.

<details>
Error: Process exited with code 16 at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:92:22) at process.emit (node:events:390:28) at process.emit (node:domain:475:12) at process.exit (node:internal/process/per_thread:184:15) at sendCrashResponse (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/logger.js:44:9) at process.<anonymous> (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:84:44) at process.emit (node:events:402:35) at process.emit (node:domain:475:12) at process._fatalException (node:internal/process/execution:164:25)
</details>

The error seems to have something to do with files not being found.

## Steps to reproduce the problem

1. Create a firebase function (https://firebase.google.com/docs/functions/get-started)
2. Deploy the function to the cloud and verify that the function works
3. Now import the @shopify/shopify-api package into your function and use it in some way
4. Deploy the function to the cloud -- function will fail to deploy
6. Downgrade your @shopify/shopify-api package to 3.0.0
7. Deploy the function to the cloud and it will succeed

## Reduced test case
---
## Checklist
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by renyuanz** [comment]
same issue here: https://github.com/Shopify/shopify-node-api/issues/389

@surma please revert the changes of v3.1.0 that making SQLite a peer-deps of session storage (https://github.com/Shopify/shopify-node-api/blob/main/src/context.ts#L46)

**Comment by cpsoinos** [comment]
Receiving a similar issue when attempting to deploy to AWS Lambda via Serverless Framework after upgrading from 3.0.1 to 3.1.0:
```
⠹ Packaging (0s)
✘ [ERROR] Could not resolve "mock-aws-s3"

    ../../node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    ../../node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

✘ [ERROR] Could not resolve "pg-native"

    ../../node_modules/pg/lib/native/client.js:4:21:
      4 │ var Native = require('pg-native')
        ╵                      ~~~~~~~~~~~

  You can mark the path "pg-native" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.
```

**Comment by harishv7** [comment]
I have the same issue when using AWS Lambda with Serverless Stack framework. Similar error as above:

```
✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

✘ [ERROR] Could not resolve "pg-native"

    node_modules/pg/lib/native/client.js:4:21:
      4 │ var Native = require('pg-native')
        ╵                      ~~~~~~~~~~~

  You can mark the path "pg-native" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.
```

Appreciate your help on this please
