### ISSUE TITLE
Better Documentation Page

### ISSUE THREAD

**Issue by davidkhierl** [Shopify/shopify-node-api#441]
## Overview

Dedicated documentation page

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

Good to have nice documentation page for developers

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this feature request in a way that is actionable (if possible)

**Comment by rohanrajpal** [comment]
+1, its quite difficult to navigate around Github README's in this repo. If the docs can be shifted to docosaurus/gitbook/shopify docs etc. it would be great!

**Comment by mkevinosullivan** [comment]
It's unclear what the actual ask is here.

The repo provides a [Getting started](https://github.com/Shopify/shopify-api-node/tree/main/docs) guide that is linked from the top-level README (https://github.com/Shopify/shopify-api-node/#getting-started)

**Comment by davidkhierl** [comment]
The README does fine but it could be improved something like Docusaurus or similar, I find it a bit extra navigating on the readme links
