### ISSUE TITLE
How to get the Shop session into database graphql schema operation  

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/shopify-node-api#493]
# Issue summary
## Shopify package version  "@shopify/shopify-api": "^5.0.1", 
how i can access 
const session =  Shopify.Utils.loadCurrentSession(req, res);
const client = new Shopify.Clients.Graphql(session.shop, session.accessToken);

 i am access the shop url from args 
```

 const session = Shopify.Utils.loadOfflineSession("offline_"+args.shop);
 const client = new Shopify.Clients.Graphql(session.shop, session.accessToken);
```
Error getting 

```{
    "message": "Missing access token when creating GraphQL client",
    "locations": [
        {
            "line": 2,
            "column": 3
        }
    ]

}
```

with graph QL operation 

my app back-end runing on the node express

express with graph QL 

i want to do some shopify graqhql into my mutation operation 
## Expected behavior

What do you think should happen?

i can access the session into Graph QL operation 

## Actual behavior
node express Graph QL operation can access the session   ` Shopify.Utils.loadCurrentSession`

What actually happens?

i want to do some graph QL operation in  withouth node ( req, res )

simple rest api i can access the Req and res object for graphql i can't

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. create any graph QL mutation on server side
2. try to access the  const session =  Shopify.Utils.loadCurrentSession(req, res);
const client = new Shopify.Clients.Graphql(session.shop, session.accessToken);
3 . getting the Error 
 `const session =  Shopify.Utils.loadCurrentSession(req, res);
                                                  ^

ReferenceError: req is not defined
`
## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://webkit.org/test-case-reduction/).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
If the `session.accessToken` is undefined/missing, this would suggest that authentication did not complete.

When Shopify sends a request to the app via the callback address (e.g. `/api/auth/callback` or whatever you choose to configure via `Shopify.Auth.beginAuth()`), using `Shopify.Auth.validateAuthCallback()` will store the session in session storage for later retrieval.

If there was no error with the authentication flow, `session.accessToken` should be populated.

**Comment by Sky-bits** [comment]
> If the `session.accessToken` is undefined/missing, this would suggest that authentication did not complete.
> 
> When Shopify sends a request to the app via the callback address (e.g. `/api/auth/callback` or whatever you choose to configure via `Shopify.Auth.beginAuth()`), using `Shopify.Auth.validateAuthCallback()` will store the session in session storage for later retrieval.
> 
> If there was no error with the authentication flow, `session.accessToken` should be populated.

@mkevinosullivan  Thanks Lot for the your Answer but i can find any reference in doc.

**Comment by mkevinosullivan** [comment]
Please review [Performing OAuth](https://github.com/Shopify/shopify-api-node/blob/main/docs/usage/oauth.md) in the usage documentation.
