### ISSUE TITLE
Property 'Billing' does not exist on type

### ISSUE THREAD

**Issue by cnscorpions** [Shopify/shopify-node-api#494]
# Issue summary

No billing export from @shopify/shopify-api

## Expected behavior

It should work
```
const {hasPayment, confirmBillingUrl} = await Shopify.Billing.check({
  session,
  isTest: true,
});
```

## Actual behavior

What actually happens?

Property 'Billing' does not exist on type '{ Context: ContextInterface; Auth: { SESSION_COOKIE_NAME: string; beginAuth(request: IncomingMessage, response: ServerResponse<IncomingMessage>, shop: string, redirectPath: string, isOnline?: boolean): Promise<...>; ... 4 more ...; getCurrentSessionId(request: IncomingMessage, response: ServerResponse<...>, isOnline...'

## Steps to reproduce the problem
1. follow your getting started guide
2. `npm install` all dependencies
"@shopify/shopify-api": "^5.0.1",
3. no billing API there

Just check github repo, billing API does exist. Maybe you guys should update @shopify/shopify-api npm module. 

Thank in advance

**Comment by coolcomfort** [comment]
I checked as well and noticed billing api is not there. Documentation and github shows that it exists, but actual files returning from npm install command appear to be different.
