### ISSUE TITLE
Improve how ensureBilling handles webhooks requests.

### ISSUE THREAD

**Issue by egillanton** [Shopify/shopify-node-api#509]
## Overview/summary

When you create a Shopify node app using the @shopify/app package...
```bash
yarn create @shopify/app
```
Then  the default app uses the verifyRequest middleware to handle all incoming API calls, including all requests to the webhook handlers.

```javascript
  app.use(
    "/api/*",
    verifyRequest(app, {
      billing: billingSettings,
    })
  );
```

A problem that I am running into is that verifyRequest relies on a session.
```javascript
  const session = await Shopify.Utils.loadCurrentSession(
      req,
      res,
      app.get("use-online-tokens")
    );
````

The session in this context is set to null.
And then it calls the hasActivePayment, passing a null  as a parameter

```javascript
async function hasActivePayment(session, { chargeName, interval }) {
  const client = new Shopify.Clients.Graphql(session.shop, session.accessToken);
```
It is tries to access member fields of the session, and we get a null reference error.

In a best case scenario, we get to following code:

```javascript
if (!hasPayment) {
    returnTopLevelRedirection(req, res, confirmationUrl);
    return;
  }
```
And then returnTopLevelRedirection will set res.status to 403, which we don't want for our webhooks. We want to always respond with a status code of 200 so our webhook will  not be automatically removed.

...

## Motivation

> What inspired this enhancement?

I am testing out different webhooks solutions using this template project.

...

### Area

- [ ] Webhooks

---

## Checklist

- [ ] I have described this enhancement in a way that is actionable (if possible)

**Comment by mkevinosullivan** [comment]
The default app generated using `yarn create @shopify/app` sets the webhook processing _before_ the use of the `verifyRequest` middleware, for this specific reason - `verifyRequest` won't work in the webhooks scenario.

https://github.com/Shopify/shopify-app-template-node/blob/cli_three/web/index.js#L79-L101

**Comment by egillanton** [comment]
@mkevinosullivan Thank you. Would be great to have ensureBilling middleware for those webhooks.

**Comment by egillanton** [comment]
in my app, for example, I have an order queue that processes the incoming orders from ORDERS_* webhooks, but I only want to enqueue the order payload if the person hasPayment.
