### ISSUE TITLE
You completely cut off Koa users.Due to the fact that this throw is thrown, it cannot be used in combination.

### ISSUE THREAD

**Issue by Koala-afurubayashi** [Shopify/shopify-node-api#554]
## Overview
You completely cut off Koa users
Due to the fact that this throw is thrown, it cannot be used in combination.
`Error: Context has not been properly initialized. Please call the .initialize() method to setup your app context object.`

@shopify/shopify-api@2.1.0 that was barely working
is no longer fully functional due to an expired version of the Admin Api.

Are you updating with developers in mind?
...

## Type

- [ ] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [ ] I have described this feature request in a way that is actionable (if possible)

**Comment by cquemin** [comment]
@Koala-afurubayashi the koa repository is deprecated and not maintained anymore.
I will encourage you, if you can, to migrate to [shopify-app-js](https://github.com/Shopify/shopify-app-js) that uses shopify-api-js. The easiest way would be for you to generate a skeleton app from our CLI and then port you business logic in the new skeleton. Here is [some documentation](https://shopify.dev/apps/getting-started/create) that can help you with the generation.
