### ISSUE TITLE
(v6) export session-utils for SessionStorage creators

### ISSUE THREAD

**Issue by deldrid1** [Shopify/shopify-node-api#562]
## Overview

Could you export `sessionFromEntries` and `sessionEntries` from `session/session-utils` similarly to `SessionStorage` and `SessionInterface`?

## Type

- [X] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

As it stands right now, all the updated repo-managed sessionStorage implementations do this:

``` typescript
import {sessionFromEntries, sessionEntries} from '../session/session-utils';
```

Unfortunately, without the export, any custom session storage doesn't get to use the built-in methods.

This leads to some anti-patterns in terms of dealing with scopes (without access to the `AuthScopes` class) as well as hacky solutions for implementing `isActive`, which is required by SessionStorage but might not be on par functionally with the native session storage implementations.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [X] I have described this feature request in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
We've addressed this by exporting the more relevant utils functions as methods in the `Session` class, which should hopefully make it easy to create your own storage adapters.

I'm going to close this since both functions you brought up have been moved, but please let us know if you still have any issues.
