### ISSUE TITLE
Shopify.Billing.check is useless for staff accounts

### ISSUE THREAD

**Issue by dxptqhtlutehvlyxcmtg** [Shopify/shopify-node-api#564]
# Issue summary

It's nice to have a billing check built in to the library, but it's currently insufficient as `Shopify.Billing.check` has no support for (all) staff accounts.

Depending on the permissions set on the staff account, responses from the GraphQL api range from working as expected, to "access denied".

Only with these excessive permissions does `check()` work:
![x](https://user-images.githubusercontent.com/108966931/195262014-121a1fa5-5b99-44b4-b26d-27777e15df5e.png)

These permssions result in `check()` throwing "access denied": (but a similar query is allowed via the REST api)
![y](https://user-images.githubusercontent.com/108966931/195262482-595852ae-36db-4cde-847f-3dbf2e805b12.png)

In the 2nd scenario, even though disallowed via Grapqhl the staff account user has access to similar information via the `recurring_application_charges` REST endpoint.

When "Manage and install apps..." is not checked, neither method works. Even with the per-app permission enabled.

## Expected behavior

At the very least, the affect of staff account permissions on `check()` should be outlined in the docs.

If the session indicates user is not a store owner, perhaps `check()` should use the REST api to query subscription status. Unfortunately, this seemingly only works if "Manage and install apps..." is enabled.

It's strange that an app can procure a valid authentication session for a user and yet lack access to basic crucial information like billing status.

## Actual behavior

As a staff account user without "Approve app charges" permission, the response from `check()` is:

```json
{
  "data": null,
  "errors": [
    {
      "message": "access denied",
      "locations": [{ "line": 4, "column": 7 }],
      "path": ["currentAppInstallation", "activeSubscriptions"]
    }
  ],
  "extensions": {
    "cost": {
      "requestedQueryCost": 2,
      "actualQueryCost": 2,
      "throttleStatus": {
        "maximumAvailable": 1000,
        "currentlyAvailable": 998,
        "restoreRate": 50
      }
    }
  }
}
```

**Comment by daviareias** [comment]
I'm using my own app and just ran into this problem, depending on the staff user permission, this query won't return any data:

`  query appSubscription {
    currentAppInstallation {
      activeSubscriptions {
        name
        test
      }
    }
  }`

Shopify is not clear about what permissions are needed to run this query, I tested on several shops that we have different degrees of access, some of them just return this:

`{
	"data": null,
	"errors": [
		{
			"message": "access denied",
			"locations": [
				{
					"line": 3,
					"column": 7
				}
			],
			"path": [
				"currentAppInstallation",
				"activeSubscriptions"
			]
		}
	],
	"extensions": {
		"cost": {
			"requestedQueryCost": 2,
			"actualQueryCost": 2,
			"throttleStatus": {
				"maximumAvailable": 1000.0,
				"currentlyAvailable": 998,
				"restoreRate": 50.0
			}
		}
	}
}`

**Comment by salehp** [comment]
This is still an active issue I'm facing. Can this be re-opened?
