### ISSUE TITLE
[6.0.0-rc7] Cannot complete OAuth process. Could not find an OAuth cookie for shop url

### ISSUE THREAD

**Issue by peernohell** [Shopify/shopify-node-api#582]
# Issue summary

We have a really basic app that work with 5.2.0. but after following migration information when we try to connect the app we have the follow error: `Cannot complete OAuth process. Could not find an OAuth cookie for shop url`

## Expected behavior

to have `Shopify.auth.callback({ isOnline: true, rawRequest: req, rawResponse: res, })` to not throw an error
We also have isOnline to `true` when we call `Shopify.auth.begin`

## Actual behavior

it throw the error.

<details>
W20221102-12:32:04.453(1)? (STDERR) (node:79490) UnhandledPromiseRejectionWarning: Error: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: laineix.myshopify.com
W20221102-12:32:04.453(1)? (STDERR)     at CookieNotFound.ShopifyError [as constructor] (/Users/peernohell/shopify/m1-rc/node_modules/@shopify/shopify-api/lib/error.js:13:28)
W20221102-12:32:04.453(1)? (STDERR)     at new CookieNotFound (/Users/peernohell/shopify/m1-rc/node_modules/@shopify/shopify-api/lib/error.js:182:42)
W20221102-12:32:04.453(1)? (STDERR)     at Object.<anonymous> (/Users/peernohell/shopify/m1-rc/node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:86:35)
W20221102-12:32:04.453(1)? (STDERR)     at step (/Users/peernohell/shopify/m1-rc/node_modules/tslib/tslib.js:144:27)
W20221102-12:32:04.453(1)? (STDERR)     at Object.next (/Users/peernohell/shopify/m1-rc/node_modules/tslib/tslib.js:125:57)
W20221102-12:32:04.453(1)? (STDERR)     at fulfilled (/Users/peernohell/shopify/m1-rc/node_modules/tslib/tslib.js:115:62)
W20221102-12:32:04.453(1)? (STDERR)     at /Users/peernohell/.meteor/packages/promise/.0.12.0.1iszf96.ge1s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20221102-12:32:04.453(1)? (STDERR)  => awaited here:
W20221102-12:32:04.453(1)? (STDERR)     at Function.Promise.await (/Users/peernohell/.meteor/packages/promise/.0.12.0.1iszf96.ge1s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20221102-12:32:04.453(1)? (STDERR)     at server/main.js:252:27
W20221102-12:32:04.453(1)? (STDERR)     at doCall (packages/meteorhacks_picker.js:128:14)
W20221102-12:32:04.453(1)? (STDERR)     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
W20221102-12:32:04.454(1)? (STDERR)     at processNextRoute (packages/meteorhacks_picker.js:90:14)
W20221102-12:32:04.454(1)? (STDERR)     at processNextRoute (packages/meteorhacks_picker.js:92:9)
W20221102-12:32:04.454(1)? (STDERR)     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
W20221102-12:32:04.454(1)? (STDERR)     at jsonParser (/Users/peernohell/shopify/m1-rc/node_modules/body-parser/lib/types/json.js:110:7)
W20221102-12:32:04.454(1)? (STDERR)     at doCall (packages/meteorhacks_picker.js:140:16)
W20221102-12:32:04.454(1)? (STDERR)     at PickerImp._processMiddleware (packages/meteorhacks_picker.js:134:5)
W20221102-12:32:04.454(1)? (STDERR)     at processNextMiddleware (packages/meteorhacks_picker.js:76:12)
W20221102-12:32:04.454(1)? (STDERR)     at urlencodedParser (/Users/peernohell/shopify/m1-rc/node_modules/body-parser/lib/types/urlencoded.js:91:7)
W20221102-12:32:04.454(1)? (STDERR)     at doCall (packages/meteorhacks_picker.js:140:16)
W20221102-12:32:04.454(1)? (STDERR)     at PickerImp._processMiddleware (packages/meteorhacks_picker.js:134:5)
W20221102-12:32:04.454(1)? (STDERR)     at processNextMiddleware (packages/meteorhacks_picker.js:76:12)
W20221102-12:32:04.454(1)? (STDERR)     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
</details>

Also, I'm on a node version `v14.19.3` and here is the cookies in the req object
```
 {
  'x-forwarded-host': 'm1.eu.ngrok.io',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'https,http',
  'x-forwarded-for': '145.224.88.122,127.0.0.1',
  'upgrade-insecure-requests': '1',
  'sec-fetch-user': '?1',
  'sec-fetch-site': 'cross-site',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-dest': 'document',
  'sec-ch-ua-platform': '"macOS"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua': '"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"',
  referer: 'https://partners.shopify.com/',
  pragma: 'no-cache',
  cookie: 'shopify_app_session=offline_laineix.myshopify.com; shopify_app_session.sig=DTCcEBKuFT0bf4lQ1GaLSdWAYxs',
  'cache-control': 'no-cache',
  'accept-language': 'en,fr;q=0.9,fr-FR;q=0.8,en-US;q=0.7',
  'accept-encoding': 'gzip, deflate, br',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
  host: 'm1.eu.ngrok.io',
  connection: 'keep-alive'
}
```

**Comment by paulomarg** [comment]
Hi folks, thanks for reporting this, and sorry for the delay in responding!

I'm noticing something strange in the example above - you're running oauth with `isOnline: true`, but the cookies you pasted seem to be for an offline session on a non-embedded app.

Could you please confirm a couple of things?

1. What is your setting for `isEmbeddedApp` when you call `shopifyApi`?
2. Was this app created with the CLI? I.e., is it an express app using our template?
3. If you look at the requests on your browser's network tab for the oauth _**begin**_ call, can you see a **_response_** header `Set-Cookie` setting a cookie named `shopify_app_state`? That is the cookie we need to have in the oauth callback request.

**Comment by peernohell** [comment]
Hi @paulomarg 
1. I just check and `isEmbeddedApp` is not set so it should be true.
2. It's a [Meteor](https://www.meteor.com/) I build. Also it's a migration of the app. The app work perfectly with version 6.0.0.
3. things start to be strange here. I restart my application with the rc7 and every things work .... The only difference is that I didn't connect with a app with older version of the shopify package and I switch from ngrok to localtunnel. Maybe on of those 2 changes make the Oauth work.

@jeff0723 if you are able to check the information requested by Paulomarg I will keep this ticket open otherwise I will close it as everything seems to work as expected now.
