### ISSUE TITLE
Multiple databases on same MySQL instance with the same session table name causes issues with Shopify.Session.MySQLSessionStorage

### ISSUE THREAD

**Issue by stevenjshelby** [Shopify/shopify-node-api#585]
# Issue summary

When you have two different databases supporting two different Shopify apps on the same MySQL host instance, the hasSessionTable() function within "/node_modules/@shopify/shopify-api/dist/auth/session/storage/mysql.js" returns incorrectly if you use the same session table name. This is because the query to check if the table exists is selecting the table name from the INFORMATION_SCHEMA table and not taking into account the database name.

## Expected behavior

I should be allowed to have the same session table name in two different databases on the same MySQL instance without any issues while using Shopify.Session.MySQLSessionStorage in Shopify.Context.initialize.

## Actual behavior

If I use the same session table name in a new app connected to the same MySQL database instance but using a different database within that instance, it will assume the session table already exists and try to access it to store/read sessions, but that will fail since the table does not actually exist in the database being used.

## Steps to reproduce the problem

1. Launch a single mysql server instance and create two databases within named "sample-app-a" and "sample-app-b".
2. Configure a new shopify-cli app to use Shopify.Session.MySQLSessionStorage with session_table name "shop_session" on database "sample-app-a".
3. Run sample-app-a in dev mode using `npm run dev`. (This should create the "shop_session" table in "sample-app-a" database)
5. Configure a second new shopify-cli app to use Shopify.Session.MySQLSessionStorage with session_table name "shop_session" on database "sample-app-b
6. Run sample-app-b in dev mode using `npm run dev`. (This should, but does not, create the "shop_session" table in "sample-app-b" database.
7. Try to load the sample app b in a test store, and an error will be thrown because it will try to query the "shop_session" table in "sample-app-b" database even though it does not exist.

**Comment by treboryx** [comment]
I'm experiencing the same issue.
