### ISSUE TITLE
[Discussion] Consider switching to a monorepo structure

### ISSUE THREAD

**Issue by tolgap** [Shopify/shopify-node-api#595]
## Overview/summary

The whole app building experience feels disconnected from each other. I'll try to explain in with multiple examples:

There are multiple repos that depend on each other right now:

- `shopify-api-node`
- `shopify-app-express`
- `shopify-app-node`
- `koa-shopify-auth`

Especially the latest addition `shopify-app-express` caught me by surprise. You would expect Express specific things to live in this repository. But it seems the entire Session Storage logic has moved there. These session storages have nothing to do with express though?

I think these choices are all symptoms of not having a place to put this code separately. I think the "shopify API" app infra could greatly benefit from a monorepo structure like Shopify/quilt.

It greatly reduces the developer burden of having to figure out where to store a piece of logic, and just create a new shareable lib in the monorepo.

So right now, I'm confused by `shopify-app-express` having the session storages. It is nothing express specific. My app doesn't use express, but Fastify. But I would like to reference these session storages for my Fastify app.

**Comment by cquemin** [comment]
[The monorepo](https://github.com/Shopify/shopify-app-js) has been created and in particular session storage are packages within it.
