### ISSUE TITLE
Blog pages to have a GraphQL mutation to add comments to articles

### ISSUE THREAD

**Issue by Ericcwong** [Shopify/shopify-node-api#661]
## Overview

Shopify liquid template has a [form](https://shopify.dev/api/liquid/tags/form#form-new_comment) component that would send a post request to the specific blog's URL. Adding a comment to the blog.

I cannot find the same option for GraphQL. Is there another route or way to add a comment on a blog article page?

**Comment by mkevinosullivan** [comment]
@Ericcwong I can't seem to find a GraphQL way either but there might be a way using the [REST API](https://shopify.dev/api/admin-rest/2023-01/resources/comment#post-comments)...
