### ISSUE TITLE
Pagination is broken in the OO REST interface

### ISSUE THREAD

**Issue by elnygren** [Shopify/shopify-node-api#740]
In the documention at https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/rest-resources.md#paginated-requests it is mentioned that:

> Note: these properties are not thread-safe because they're stored statically in the class. If you are using this feature to send requests in parallel, you can store the query property in a thread-safe way, since it's a plain JavaScript object.

However, it is impossible to do so because you abstract away the `Response` (that has `response.pageInfo?.nextPage`, see: https://github.com/Shopify/shopify-api-js/blob/d606b9dad669c095825f0a1e9544ce47b6f267ea/rest/base.ts#L85)

So it's not possible to do what your Docs suggest and this API client is pretty much useless for any real world application that will certainly have numerous parallel requests going on at all times.

## Example

```typescript
do {
  // note that we can't access the `response` here
  const pageProducts: Products[] = await shopify.rest.Product.all({
    ...shopify.rest.Product.NEXT_PAGE_INFO?.query,
    session,
    status: 'active',
  });

  // if we store `shopify.rest.Product.NEXT_PAGE_INFO?.query` here, it is not guaranteed to have the correct data as 
  // we might already have resolved other API requests that are running at the same time elsewhere in our event loop

} while (shopify.rest.Product.NEXT_PAGE_INFO);
```

## Solution

The current implementation with the static class variable is fundamentally wrong in an asynchronous platform like Node.js and should be changed so that you actually return the pagination related data to the caller. 

Another alternative could be that every caller creates a separate class instance and you'd use instance variables for the pagination. However, that's a bit dangerous as people might not remember to do it.

**Comment by akx** [comment]
This is also problematic in that another module in the program (maybe a third-party library) may be in a loop like the above in a parallel call, and you're none the wiser that something that's out of your control is clobbering your `NEXT_PAGE_INFO`s in the background.

**Comment by paulomarg** [comment]
Thanks for pointing this out folks. You're right in that there is no guarantee that there won't be race conditions even if you save the page info locally after the request.

We've updated these calls so that they'll return both the `data` and the `pageInfo` directly. It's a small breaking change but it should fix this issue when we release v7.

Thank you for your feedback!
