### ISSUE TITLE
Unable to use environment variables in development mode

### ISSUE THREAD

**Issue by Syed-Huzaifa1** [Shopify/shopify-node-api#750]
# Issue summary
I created a new shopify app (node-react) using the shopify-cli and then I created a .env file in the root folder and ran the `npm run shopify app env pull` command. The relevant environment variables were added to my .env file but I am not able to access them in the code right now.

- Node version: 18
- Operating system: MacOS

## Expected behavior

Should return the relevant environment variables when I log them.

## Actual behavior

Only returns the default created variables which were generated when I ran the `npm run shopify app env pull` command.

## Steps to reproduce the problem

1. Create a new app using shopify-cli
2. Install the app in store
3. Run the app using `npm run dev`

**Comment by mkevinosullivan** [comment]
`npm run shopify app env pull` will generate a `.env` file but I don't think it uses that file when passing environment variables into the application (it builds the environment independently of `.env`).

To pull the variables in `.env` into your app, you'll need to add something like the `dotenv` package (to `web/package.json`) and add
```js
import * as dotenv from 'dotenv';
dotenv.config();
```
to the `index.js` file.

**Comment by Syed-Huzaifa1** [comment]
> Yes, that is correct ... I should have mentioned that it needs to be inside the `web` folder (where the app server is), not the root folder (which is mainly for the CLI).

Can you help me out with something else as well though?
When I run the app using `npm run dev`, it automatically generates an ngrok URL and asks me to update the App URLs inside the partners' dashboard. Is there a way I can give it a static ngrok URL and not the one it generates by default?

**Comment by VIVO36** [comment]
> Yes, that is correct ... I should have mentioned that it needs to be inside the `web` folder (where the app server is), not the root folder (which is mainly for the CLI).

I tried this and it didn't work. 

1. The .env file is in web folder

2. dotenv is installed & showing in web/package.json

3. index.js file contains: 
import * as dotenv from 'dotenv';
dotenv.config();

4. restarted the server countless times in between every change

this is how I am accessing my key: process.env.KEY_NAME

Any advice to troubleshoot this?
