### ISSUE TITLE
 CustomSessionStorage failed to load a session

### ISSUE THREAD

**Issue by adventuretocode** [Shopify/shopify-node-api#756]
# Issue summary
custom session with mongoDB db not loading right custom session.

- `@shopify/shopify-api` version: "@shopify/shopify-api": "^5.2.0"
- Node version: v16
- Operating system: Ubuntu 

```
// Paste any relevant logs here

 SessionStorageError: CustomSessionStorage failed to load a session. Error Details: Error: Unsupported state or unable to authenticate data
         |     at SessionStorageError.ShopifyError [as constructor] ( /node_modules/@shopify/shopify-api/dist/error.js:13:28)
         |     at new SessionStorageError ( /node_modules/@shopify/shopify-api/dist/error.js:206:42)
         |     at CustomSessionStorage.<anonymous> ( /node_modules/@shopify/shopify-api/dist/auth/session/storage/custom.js:51:31)
         |     at step ( /node_modules/tslib/tslib.js:144:27)
         |     at Object.throw ( /node_modules/tslib/tslib.js:125:57)
         |     at rejected ( /node_modules/tslib/tslib.js:116:69)
         |     at processTicksAndRejections (node:internal/process/task_queues:96:5


```

## Expected behavior
customer session load correct.
 

## Actual behavior
fail to load custom session from shopify library 

## Steps to reproduce the problem

1.
1.
1.

**Comment by mkevinosullivan** [comment]
The implementation of custom storage is developer-specific and outside the scope of this library.  The error indicated above is from the `loadSessionCallback` passed in during initialization, i.e., it's from the custom storage implementation itself.
