### ISSUE TITLE
Why is `webhooks.addHandlers` async?

### ISSUE THREAD

**Issue by j** [Shopify/shopify-node-api#761]
In the latest api client, `addHandlers` is async but most examples I'm seeing call it synchronously.

i.e. https://github.com/Shopify/shopify-app-js/blob/16f88fc9966887e73e11b052d7d7d584700e5b76/packages/shopify-app-express/src/webhooks/index.ts#L42

Is there a design reason for leaving it async?

I see that the update guide mentions it being asynchronous, but I'm unclear why.

I'm trying to implement handler registration in a Next.js app but there's no way to really "bootstrap" asynchronous things in a performant manner.

**Comment by mkevinosullivan** [comment]
@j Thanks for highlighting that ... those calls in the `shopify-app-express` package should have `await` in front of them, will add to the backlog.

The reason the `addHandlers` is `async` is because of an underlying logging mechanism called within the method itself.
