### ISSUE TITLE
Version 7.1.0 breaks bundle compiled using webpack

### ISSUE THREAD

**Issue by brendenpalmer** [Shopify/shopify-node-api#889]
# Issue summary

Webpack doesn't like `require` statements using a variable (https://github.com/Shopify/shopify-api-js/blob/main/runtime/crypto/crypto.ts#L9), as it tries to bundle modules via static analysis, and as a result the compiled output can't find the `crypto` module. Webpack attempts to bundle the module (that it can't resolve statically) when creating the bundle, and ultimately produces an error as part of the bundled output.

- `@shopify/shopify-api` version: 7.1.0
- Node version: 18.6.0
- Operating system: Mac OS

## Expected behavior

Should be able to be bundled with webpack (as is possible on v7.0.0 and v6).

## Actual behavior

Webpack creates a bundle with a module that it thinks it can't resolve statically.

## Steps to reproduce the problem

1. Checkout this repo: https://github.com/brendenpalmer/shopify-api-v7.1.0-webpack-issue-repro
1. Ensure [Volta](https://volta.sh/) is installed
1. Run `yarn install`
1. Run `yarn build`
1. Run `node dist/main.js`

**Comment by theaveasso** [comment]
Hey @brendenpalmer, I also have the same problem. Got this issue while compile and running. Your repo was successfully run when I downgrade it to `^7.0.0` but mine is not working at that version, still don't know why.

**Comment by brendenpalmer** [comment]
@theaveasso it's possible you're still getting `7.1.0` or `7.2.0` resolved in your lock file due to `^` usage; did you try pinning to `7.0.0` explicitly (i.e., with no `^` prior to version in `package.json`)?

**Comment by theaveasso** [comment]
@brendenpalmer Oh yes, Thank you ,now it works with 7.0.0.

**Comment by Magzter** [comment]
Similar issue but with the network package, running on 7.0.0 does work for me as an interim solution

```
{
    "errorType": "Error",
    "errorMessage": "require() of ES Module /ommited/node_modules/@shopify/network/build/esm/index.mjs not supported.\nInstead change the require of /opt/nodejs/node_modules/ommited/node_modules/@shopify/network/build/esm/index.mjs to a dynamic import() which is available in all CommonJS modules.",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/nodejs/node_modules/ommited/node_modules/@shopify/network/build/esm/index.mjs not supported.",
        "Instead change the require of /opt/nodejs/node_modules/ommited/node_modules/@shopify/network/build/esm/index.mjs to a dynamic import() which is available in all CommonJS modules.",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/node_modules/@shopify/network/index.js:5:14)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/node_modules/@shopify/shopify-api/lib/clients/http_client/http_client.js:7:19)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/node_modules/@shopify/shopify-api/lib/clients/index.js:6:23)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/node_modules/@shopify/shopify-api/lib/index.js:11:19)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/src/shopify/sessionStorage/secrets.js:12:21)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/src/shopify/sessionStorage/index.js:6:14)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/src/shopify/config.js:19:25)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/src/shopify/index.js:28:17)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/src/shopify.js:5:14)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/ommited/index.js:12:14)",
        "    at Object.<anonymous> (/var/task/lambda/shopify/auth/login.js:25:21)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:912:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:962:25)",
        "    at _loadUserApp (file:///var/runtime/index.mjs:991:22)",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1032:27)",
        "    at start (file:///var/runtime/index.mjs:1195:42)",
        "    at file:///var/runtime/index.mjs:1201:7",
        "    at async Promise.all (index 0)"
    ]
}

```
