### ISSUE TITLE
How can I register new hooks handler without re-install app ?

### ISSUE THREAD

**Issue by st-hungdinh** [Shopify/shopify-node-api#944]
## Overview/summary

Hi, I am developing an Shopify app. But when i add new webhook handler, i must re-install app again manually. 
Have any solution to register new hooks without re-install app ?

https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/webhooks/register.md
```
Webhooks can only be registered after the merchant has installed your app, so the best place to register webhooks is after OAuth completes.
```

**Comment by pullmann4rent** [comment]
Get the session ID and then:

```
const webhook = new shopify.rest.Webhook({session: session});
webhook.address = "pubsub://projectName:topicName";
webhook.topic = "customers/update";
webhook.format = "json";
await webhook.save({
  update: true,
});
```

Get it from admin api docs I do not try it yet
