### ISSUE TITLE
HMAC docs are misleading

### ISSUE THREAD

**Issue by jonathanstanley** [Shopify/shopify-node-api#981]
# Issue summary

## 1. test HTTPS?
Shopify docs for hooks state that app developers should [verify hooks sent using HTTPS](https://shopify.dev/docs/apps/webhooks#webhook-headers):
<img width="932" alt="Screenshot 2023-09-06 at 12 03 42 PM" src="https://github.com/Shopify/shopify-api-js/assets/2755958/cc1ac5ad-6b35-446a-9e4f-4b924708425f">

However, the linked docs to verify hooks actually do not verify HTTPS. [Instead it asks devs to verify the HMAC](https://shopify.dev/docs/apps/webhooks/configuration/https#step-5-verify-the-webhook). Checking HTTPS would have been much more straightforward.

## 2. provide a validator?
Although Shopify does have an HMAC validator as part of the standard js kit, [it isn't usable and fails](https://github.com/Shopify/shopify-api-js/issues/878#issuecomment-1685112157). 

Shopify also has  [`shopify.api.webhooks.validate()`](https://github.com/Shopify/shopify-api-js/blob/b583318fec076e262234d6f20724dbb9d5ab78a2/lib/webhooks/validate.ts#L33) for [javascript api](https://github.com/Shopify/shopify-api-js/blob/main/docs/guides/webhooks.md) but it [isn't declared in the main docs](https://shopify.dev/docs/apps/webhooks/configuration/https#step-5-verify-the-webhook)?

## 3. what to use for HMAC?

for hmac data:
* **webhooks** data is the [`req.body` `string` before any parsing](https://shopify.dev/docs/apps/webhooks/configuration/https#step-5-verify-the-webhook) (re-serializing from the built-in express.js JSON middleware is inefficient and could break us). 
* **app proxy** data is [partial query parameters](https://shopify.dev/docs/apps/online-store/app-proxies#calculate-a-digital-signature), without the signature, ordered, then custom serialization
* **authenticated fetch** hmac data is[ integrated into a normal JWT](https://shopify.dev/docs/apps/auth/oauth/session-tokens/getting-started#step-3-decode-session-tokens-for-incoming-requests) 🎉 hurrah using the authorization header for auth!

for hmac value:
* **webhooks** keep the hmac in the header `x-shopify-hmac-sha256`.
* **app proxy** stuffs the hmac into the query parameter `signature` 
* **authenticated fetch** hmac value is consistent with JWT specifications

for hmac digest encoding
* **webhooks**  uses [`base64`](https://shopify.dev/docs/apps/webhooks/configuration/https#step-5-verify-the-webhook).
* **app proxy** uses [`hex`](https://shopify.dev/docs/apps/online-store/app-proxies#calculate-a-digital-signature)
* **authenticated fetch** uses [`HS256`](https://shopify.dev/docs/apps/auth/oauth/session-tokens/getting-started#step-3-decode-session-tokens-for-incoming-requests) ([`base64-url` per JWT spec](https://www.iana.org/assignments/jose/jose.xhtml))

and there are other situations in shopify that use [tokens, oauth](https://shopify.dev/docs/apps/auth#types-of-authentication-and-authorization-methods) and [cookies](https://shopify.dev/docs/apps/auth/oauth/session-tokens).

why not just use JWT in each of these cases?

# Expected behavior

each of these contrived hmac schemes could be replaced with JWT. next best would be some consistency. or sample code:

```js
/** tests an hmac value against the data as imposed by shopify  */
function verifyHmac(
  /** @type {string} */ data,
  /** @type {string} */ unverifiedHmac,
  /**
   * @note
   * * Shopify uses hex digest for app proxy https://shopify.dev/docs/apps/online-store/app-proxies#calculate-a-digital-signature
   * * Shopify uses base64 digest for webhooks https://shopify.dev/docs/apps/webhooks/configuration/https#step-5-verify-the-webhook
   * @type { import("crypto").BinaryToTextEncoding} */ encoding
) {
  const verifiedHmac = createHmac("sha256", shopify.api.config.apiSecretKey)
    .update(data) // accepts string or ArrayBufferView; we'll just use string
    .digest(encoding);
  return unverifiedHmac === verifiedHmac;
}
```

# Actual behavior

🤯

**Comment by ashleyww93** [comment]
In my experience, the docs are misleading for almost everything I have tried to do so far...
