### ISSUE TITLE
metafieldsSet type can not be blank | version 2023-07

### ISSUE THREAD

**Issue by gulam-quinn** [Shopify/shopify-node-api#990]
Experiencing a problem with Shopify's GraphQL Admin API (version 2023-07) while updating metafields. Despite the API documentation indicating that the type field is nullable for existing metafields, an error stating "Type can't be blank" persists during updates. This issue hampers the expected simplification of the metafield mutation process.

I've recently encountered an issue with the GraphQL Admin API update in the 2023-07 release, specifically related to the metafieldsSet API. According to the documentation, as part of the 2023-01 GraphQL Admin API release, the MetafieldsSetInput.type field was made nullable. This change was intended to simplify the mutation process for updating metafields.

Here's the relevant information from Shopify's announcement:

"As part of the 2023-01 GraphQL Admin API release, we've updated the metafieldsSet API to make the MetafieldsSetInput.type field nullable. When the metafield you are trying to mutate already has corresponding metafield definitions, you can simplify the mutation by omitting the type field from its arguments. The type field is still required when the metafield doesn't have a corresponding definition to the given ownerId, namespace, and key."

However, despite upgrading to the 2023-07 API version and following the updated documentation, I'm still encountering an issue where I receive a "Type can't be blank" error when trying to update a metafield. I've thoroughly tested this with various namespace, key, and ownerId values to ensure that I'm not making any mistakes in my implementation.

## Expected behavior

I expected that with the update in the 2023-07 API version, I would be able to omit the type field when updating a metafield as long as the metafield already exists and has corresponding definitions, as specified in the documentation.

## Actual behavior
However, despite following the documentation and upgrading to the 2023-07 API version, I continue to receive a "Type can't be blank" error when attempting to update a metafield, even in cases where the metafield already exists.

- `@shopify/shopify-api` version: 2023-07
- Node version: 18
- Operating system: MacOS

Sending this payload, namespace, key and ownerId combo already exist.
```
 {
  "namespace": "settings",
  "key": "developer_mode",
  "value": "true",
  "ownerId": "gid://shopify/AppInstallation/999999999"
}

{
  "data": {
    "metafieldsSet": {
      "metafields": [],
      "userErrors": [
        {
          "field": [
            "metafields",
            "0",
            "type"
          ],
          "message": "Type can't be blank",
          "__typename": "MetafieldsSetUserError"
        }
      ],
      "__typename": "MetafieldsSetPayload"
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 10,
      "actualQueryCost": 10,
      "throttleStatus": {
        "maximumAvailable": 1000,
        "currentlyAvailable": 990,
        "restoreRate": 50
      }
    }
  }
}
```

It seems that this change in the API does not simplify the metafield mutation process as intended. It now requires an additional step of checking whether a metafield exists before making an update, which was not the case prior to this API update. This extra step adds complexity and could potentially lead to errors.

**Comment by avocadoslab** [comment]
We are running into exact same issue! If we leave it as is then we get warning but get error on removal!

**Comment by gulam-quinn** [comment]
The type is optional only when a **Metafield definition** exist for the Metafield, but the issue is that none of our metafield has definitions created. 

To solve this issue i tried to create metafield definitions for each metafield, but apparently you can't create metafield definition with owner type API_PERMISSIONS, nowhere in doc this is mentioned.
